// This code is auto-generated by Qul's qmlinterfacegenerator tool from file '/home/stvsl/Documents/DOTRUST/MCUDemo/MCUDemo/src/bredge/AppBredge.h'
// WARNING! All changes made in this file will be lost!

pragma qmlinterface;
pragma Singleton;
pragma cppname$AppBredge;
import "/home/stvsl/Documents/DOTRUST/MCUDemo/MCUDemo/src/bredge/AppBredge.h";
import QtQuick;

Singleton {
    function onEvent(event : bool)  {}
    function subscribe(event, callback)  {}
    function publish(event, args)  {}
}
