// This code is auto-generated by Qul's qmlinterfacegenerator tool from file '/home/stvsl/Documents/DOTRUST/MCUDemo/MCUDemo/src/daemon/Daemon.h'
// WARNING! All changes made in this file will be lost!

pragma qmlinterface;
pragma Singleton;
pragma cppname$Daemon;
import "/home/stvsl/Documents/DOTRUST/MCUDemo/MCUDemo/src/daemon/Daemon.h";
import QtQuick;

Singleton {
    enum EventType { LED_STATUS_CHANGED = 0, COUNT = 1 }
    property int led_status;
    function pushEvent(event : int, value : int)  {}
}
