// WARNING: This file is auto-generated by qmlprojectexporter
// Don't edit it. Any changes will be overwritten.

namespace Qul {
namespace Private {

// primaryLanguage is the language applied at startup.
// When this is an empty string, the source text from QML is used.
const char *primaryLanguage = "";

} // namespace Private
} // namespace Qul
