// This code is auto-generated by qulprojectexporter tool.
// WARNING! All changes made in this file will be lost!

#include <qul/private/qul_app_config.h>

namespace Qul {
namespace Private {

const int displayRotationAngle = 0;
const bool showDesktopPreviewInNaturalDisplayOrientation = true;
const bool isTargetPlatformDesktop = 0;

} // namespace Private
} // namespace Qul
