// This code is auto-generated by Qul's qmltocpp tool from the file 'Button.qml'
// WARNING! All changes made in this file will be lost!
#include "Button.h"
#include <qul/private/graphicsdevice.h>
#include <qul/private/filecache.h>

extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_button_2Dpressed_11482530446956379099_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_button_15269041248754601604_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_button_2Ddisabled_9672076571956466492_handle;
static const Qul::Private::String qulCurrentFileDir(".", 1);
namespace QtQuick {
namespace Controls {
namespace StyleDefault {
extern Qul::Private::Items::ItemBase *loaderItemAllocator(const Qul::Private::String &uri, const Qul::Private::String &currentFileDir);

} // namespace QtQuick
} // namespace Controls
} // namespace StyleDefault
namespace Qul { namespace Private {
Qul::Property<int> &translationIndexProperty_da39a3ee5e6b4b0d3255bfef95601890afd80709();
extern const uint32_t *qul_translation_offsets_1aed64446b5113f8d53f2b33c838e162dc86bf55();
extern const uint8_t *qul_translations_1aed64446b5113f8d53f2b33c838e162dc86bf55();
}}

namespace QtQuick {
namespace Controls {
namespace StyleDefault {

namespace {
#if defined(QUL_CC_IAR)
#pragma diag_suppress=Pe177 // declared but never referenced
#elif defined(QUL_CC_GNU)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-function"
#endif
static Qul::Property<int> &translationIndexProperty() { return Qul::Private::translationIndexProperty_da39a3ee5e6b4b0d3255bfef95601890afd80709(); }
static int translationIndex() { return translationIndexProperty().value(); }
static const char *qul_translation(int entry) {
    const size_t translationLanguageCount = 1;
    const uint32_t *offsets = Qul::Private::qul_translation_offsets_1aed64446b5113f8d53f2b33c838e162dc86bf55();
    const uint8_t *translations = Qul::Private::qul_translations_1aed64446b5113f8d53f2b33c838e162dc86bf55();
    return reinterpret_cast<const char *>(&translations[offsets[entry * translationLanguageCount + translationIndex()]]);
}
#if defined(QUL_CC_IAR)
#pragma diag_default=Pe177 // declared but never referenced
#elif defined(QUL_CC_GNU)
#pragma GCC diagnostic pop
#endif
}


int Button::borderimage_width_anchor_bindingFunctor::operator()(Button *self) const {
        return int(self->item_.width.value());
}
int Button::borderimage_height_anchor_bindingFunctor::operator()(Button *self) const {
        return int(self->item_.height.value());
}
Qul::SharedImage Button::Button_1543837591_bindingFunctor::operator()(Button *self) const
{
    (void) self;
    bool r2__down;
    QUL_DECL_UNUSED Button * r2 = NULL;
    QUL_DECL_UNUSED Qul::Private::String r2_1;
    // source: control.enabled
    // line 63  "Button.qml"
    r2 = self;
    r2__down = r2->enabled.value();
    if (!r2__down) goto label_0;;
    r2 = self;
    // ? (control.down ? "qrc:/images/button-pressed.png" : "qrc:/images/button.png")
    // line 64  "Button.qml"
    r2__down = r2->down.value();
    if (!r2__down) goto label_1;;
    r2_1 = Qul::Private::String(Qul::Private::ImageIdValue::create("qrc:/images/button-pressed.png", qul_rasterBuffer_button_2Dpressed_11482530446956379099_handle), 30);
    goto label_2;;
    label_1:;
    r2_1 = Qul::Private::String(Qul::Private::ImageIdValue::create("qrc:/images/button.png", qul_rasterBuffer_button_15269041248754601604_handle), 22);
    label_2:;
    goto label_3;;
    label_0:;
    r2_1 = Qul::Private::String(Qul::Private::ImageIdValue::create("qrc:/images/button-disabled.png", qul_rasterBuffer_button_2Ddisabled_9672076571956466492_handle), 31);
    label_3:;
    // : "qrc:/images/button-disabled.png"
    // line 65  "Button.qml"
    return Qul::Private::findImageForString(r2_1);
    
}
Qul::PlatformInterface::Rgba32 Button::Button_1995920566_bindingFunctor::operator()(Button *self) const
{
    (void) self;
    QUL_DECL_UNUSED Qul::PlatformInterface::Rgba32 r2__disabledTextColor;
    bool r2__enabled;
    QUL_DECL_UNUSED Button * r2 = NULL;
    QUL_DECL_UNUSED  ::QtQuick::Controls::StyleDefault::DefaultStyle * r2_3 = NULL;
    // color: control.enabled ? DefaultStyle.textColor : DefaultStyle.disabledTextColor
    // line 49  "Button.qml"
    r2 = self;
    r2__enabled = r2->enabled.value();
    if (!r2__enabled) goto label_0;;
    r2_3 = & ::QtQuick::Controls::StyleDefault::DefaultStyle ::instance();
    r2__disabledTextColor = r2_3->textColor.value();
    goto label_1;;
    label_0:;
    r2_3 = & ::QtQuick::Controls::StyleDefault::DefaultStyle ::instance();
    r2__disabledTextColor = r2_3->disabledTextColor.value();
    label_1:;
    return r2__disabledTextColor;
    
}
Qul::Private::FontPointer Button::Button_3934977972_bindingFunctor::operator()(Button *self) const
{
    (void) self;
    QUL_DECL_UNUSED Button * r2 = NULL;
    QUL_DECL_UNUSED Qul::Private::FontPointer r2__font;
    // font: control.font
    // line 48  "Button.qml"
    r2 = self;
    r2__font = r2->font.value();
    return r2__font;
    
}
Qul::Private::String Button::Button_1880257050_bindingFunctor::operator()(Button *self) const
{
    (void) self;
    QUL_DECL_UNUSED Button * r2 = NULL;
    QUL_DECL_UNUSED Qul::Private::String r2__text;
    // text: control.text
    // line 47  "Button.qml"
    r2 = self;
    r2__text = r2->text.value();
    return r2__text;
    
}
int Button::Button_638361119_bindingFunctor::operator()(Button *self) const
{
    (void) self;
    int r2_2;
    Qul::qreal r2_1;
    QUL_DECL_UNUSED Qul::Private::Builtins::Math * r2 = NULL;
    QUL_DECL_UNUSED Qul::Private::Items::ItemBase * r2_3 = NULL;
    int r10;
    int r12;
    int r11;
    QUL_DECL_UNUSED Qul::Private::Builtins::Math * r7 = NULL;
    int r13;
    // implicitHeight: Math.max((background ? background.implicitHeight : 0) + topInset + bottomInset,
    // line 30  "Button.qml"
    r2 = &Qul::Private::Builtins::Math ::instance();
    r7 = r2;
    r2_3 = self->background.value();
    if (!r2_3) goto label_0;;
    r2_3 = self->background.value();
    r2_2 = r2_3->itemExtraProperties->implicitHeight.value();
    goto label_1;;
    label_0:;
    r2_2 = 0;
    label_1:;
    r12 = r2_2;
    r2_2 = self->topInset.value();
    r2_2 = r12 + r2_2;
    r13 = r2_2;
    r2_2 = self->bottomInset.value();
    r2_2 = r13 + r2_2;
    r10 = r2_2;
    // (contentItem ? contentItem.implicitHeight : 0) + topPadding + bottomPadding)
    // line 31  "Button.qml"
    r2_3 = self->contentItem.value();
    if (!r2_3) goto label_2;;
    r2_3 = self->contentItem.value();
    r2_2 = r2_3->itemExtraProperties->implicitHeight.value();
    goto label_3;;
    label_2:;
    r2_2 = 0;
    label_3:;
    r12 = r2_2;
    r2_2 = self->topPadding.value();
    r2_2 = r12 + r2_2;
    r13 = r2_2;
    r2_2 = self->bottomPadding.value();
    r2_2 = r13 + r2_2;
    r11 = r2_2;
    r2_1 = r7->max(r10, r11);
    return int(r2_1);
    
}
int Button::Button_2791446706_bindingFunctor::operator()(Button *self) const
{
    (void) self;
    int r2_2;
    Qul::qreal r2_1;
    QUL_DECL_UNUSED Qul::Private::Builtins::Math * r2 = NULL;
    QUL_DECL_UNUSED Qul::Private::Items::ItemBase * r2_3 = NULL;
    int r10;
    int r12;
    int r11;
    QUL_DECL_UNUSED Qul::Private::Builtins::Math * r7 = NULL;
    int r13;
    // implicitWidth: Math.max((background ? background.implicitWidth : 0) + leftInset + rightInset,
    // line 28  "Button.qml"
    r2 = &Qul::Private::Builtins::Math ::instance();
    r7 = r2;
    r2_3 = self->background.value();
    if (!r2_3) goto label_0;;
    r2_3 = self->background.value();
    r2_2 = r2_3->itemExtraProperties->implicitWidth.value();
    goto label_1;;
    label_0:;
    r2_2 = 0;
    label_1:;
    r12 = r2_2;
    r2_2 = self->leftInset.value();
    r2_2 = r12 + r2_2;
    r13 = r2_2;
    r2_2 = self->rightInset.value();
    r2_2 = r13 + r2_2;
    r10 = r2_2;
    // (contentItem ? contentItem.implicitWidth : 0) + leftPadding + rightPadding)
    // line 29  "Button.qml"
    r2_3 = self->contentItem.value();
    if (!r2_3) goto label_2;;
    r2_3 = self->contentItem.value();
    r2_2 = r2_3->itemExtraProperties->implicitWidth.value();
    goto label_3;;
    label_2:;
    r2_2 = 0;
    label_3:;
    r12 = r2_2;
    r2_2 = self->leftPadding.value();
    r2_2 = r12 + r2_2;
    r13 = r2_2;
    r2_2 = self->rightPadding.value();
    r2_2 = r13 + r2_2;
    r11 = r2_2;
    r2_1 = r7->max(r10, r11);
    return int(r2_1);
    
}

Button::Button()

    : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Controls::Templates::Button  >(this)
    , borderimage_width_anchor_binding(borderimage_width_anchor_bindingFunctor())
    , borderimage_height_anchor_binding(borderimage_height_anchor_bindingFunctor())
    , borderimage_source_binding(Button_1543837591_bindingFunctor())
    , text__color_binding(Button_1995920566_bindingFunctor())
    , font_font_binding(Button_3934977972_bindingFunctor())
    , text__text_binding(Button_1880257050_bindingFunctor())
    , _implicitHeight_binding(Button_638361119_bindingFunctor())
    , _implicitWidth_binding(Button_2791446706_bindingFunctor())
{
    // implicitHeight: 66
    // line 56  "Button.qml"
    item_.itemExtraProperties->implicitHeight.setValue(66);
    // implicitWidth: 136
    // line 55  "Button.qml"
    item_.itemExtraProperties->implicitWidth.setValue(136);
    // BorderImage {
    // line 58  "Button.qml"
    appendChild(&this->item_, &borderimage);
    borderimage.x.setValue(int());
    borderimage_width_anchor_binding.init<Button, &Button::borderimage_width_anchor_binding>(borderimage.width);
    borderimage.width.setBinding(&borderimage_width_anchor_binding);
    borderimage.y.setValue(int());
    borderimage_height_anchor_binding.init<Button, &Button::borderimage_height_anchor_binding>(borderimage.height);
    borderimage.height.setBinding(&borderimage_height_anchor_binding);
    borderimage_source_binding.init<Button, &Button::borderimage_source_binding>(borderimage.source);
    // source: control.enabled
    // line 63  "Button.qml"
    borderimage.source.setBinding (&borderimage_source_binding);
    // border.bottom: 27
    // line 62  "Button.qml"
    borderimage.border.bottom.setValue(27);
    // border.right: 22
    // line 61  "Button.qml"
    borderimage.border.right.setValue(22);
    // border.left: 22
    // line 60  "Button.qml"
    borderimage.border.left.setValue(22);
    // border.top: 18
    // line 59  "Button.qml"
    borderimage.border.top.setValue(18);
    // background: Item {
    // line 54  "Button.qml"
    background.setValue(&item_);
    // verticalAlignment: Text.AlignVCenter
    // line 51  "Button.qml"
    text_.verticalAlignment.setValue(Qul::Private::Items::Text::AlignVCenter);
    // horizontalAlignment: Text.AlignHCenter
    // line 50  "Button.qml"
    text_.horizontalAlignment.setValue(Qul::Private::Items::Text::AlignHCenter);
    text__color_binding.init<Button, &Button::text__color_binding>(text_.color);
    // color: control.enabled ? DefaultStyle.textColor : DefaultStyle.disabledTextColor
    // line 49  "Button.qml"
    text_.color.setBinding (&text__color_binding);
    font_font_binding.init<Button, &Button::font_font_binding>(text_.font);
    // font: control.font
    // line 48  "Button.qml"
    text_.font.setBinding (&font_font_binding);
    text__text_binding.init<Button, &Button::text__text_binding>(text_.text);
    // text: control.text
    // line 47  "Button.qml"
    text_.text.setBinding (&text__text_binding);
    // contentItem: Text {
    // line 46  "Button.qml"
    contentItem.setValue(&text_);
    // bottomInset: DefaultStyle.inset - 18
    // line 44  "Button.qml"
    bottomInset.setValue(-13);
    // rightInset: DefaultStyle.inset - 12
    // line 43  "Button.qml"
    rightInset.setValue(-7);
    // topInset: DefaultStyle.inset - 6
    // line 42  "Button.qml"
    topInset.setValue(-1);
    // leftInset: DefaultStyle.inset - 12
    // line 41  "Button.qml"
    leftInset.setValue(-7);
    // bottomPadding: 16
    // line 36  "Button.qml"
    bottomPadding.setValue(16);
    // rightPadding: 16
    // line 35  "Button.qml"
    rightPadding.setValue(16);
    // topPadding: 22
    // line 34  "Button.qml"
    topPadding.setValue(22);
    // leftPadding: 16
    // line 33  "Button.qml"
    leftPadding.setValue(16);
    _implicitHeight_binding.init<Button, &Button::_implicitHeight_binding>(itemExtraProperties->implicitHeight);
    // implicitHeight: Math.max((background ? background.implicitHeight : 0) + topInset + bottomInset,
    // line 30  "Button.qml"
    itemExtraProperties->implicitHeight.setBinding (&_implicitHeight_binding);
    _implicitWidth_binding.init<Button, &Button::_implicitWidth_binding>(itemExtraProperties->implicitWidth);
    // implicitWidth: Math.max((background ? background.implicitWidth : 0) + leftInset + rightInset,
    // line 28  "Button.qml"
    itemExtraProperties->implicitWidth.setBinding (&_implicitWidth_binding);
}

} // namespace QtQuick
} // namespace Controls
} // namespace StyleDefault
