// This code is auto-generated by Qul's qmltocpp tool from the file 'Button.qml'
// WARNING! All changes made in this file will be lost!
// NOTE: This generated API is to be considered implementation detail for Qul.
//       It may change from version to version and should not be relied upon.
#pragma once
#include "DefaultStyle.h"
#include <platforminterface/log.h>
#include <qul/image.h>
#include <qul/private/builtins.h>
#include <qul/private/controls/buttontemplate.h>
#include <qul/private/file.h>
#include <qul/private/items.h>
#include <qul/private/items/item.h>
#include <qul/private/items/text.h>
#include <qul/private/qulrcc_lookup.h>
#include <qul/private/unicodestring.h>
#include <qul/signal.h>

namespace QtQuick {
namespace Controls {
namespace StyleDefault {

struct Button : Qul::Private::Controls::Templates::Button , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Controls::Templates::Button  > {
    Button();


    Qul::Property<Qul::Private::String> state;
    typedef Qul::Private::Items::BorderImage  borderimage_BorderImage;
    borderimage_BorderImage borderimage;
    struct item__Item : Qul::Private::Items::Item , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Item  > {
        item__Item()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Item  >(this)
        {}
    } item_;
    struct text__Text : Qul::Private::Items::Text , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Text  > {
        text__Text()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Text  >(this)
        {}
    } text_;
    struct borderimage_width_anchor_bindingFunctor {
    int operator()(Button *self) const;
};
    Qul::Private::Binding<borderimage_width_anchor_bindingFunctor, 1> borderimage_width_anchor_binding;
    struct borderimage_height_anchor_bindingFunctor {
    int operator()(Button *self) const;
};
    Qul::Private::Binding<borderimage_height_anchor_bindingFunctor, 1> borderimage_height_anchor_binding;
    struct Button_1543837591_bindingFunctor {
        Qul::SharedImage operator()(Button *self) const;
    };
    Qul::Private::Binding<Button_1543837591_bindingFunctor, 0> borderimage_source_binding;
    struct Button_1995920566_bindingFunctor {
        Qul::PlatformInterface::Rgba32 operator()(Button *self) const;
    };
    Qul::Private::Binding<Button_1995920566_bindingFunctor, 0> text__color_binding;
    struct Button_3934977972_bindingFunctor {
        Qul::Private::FontPointer operator()(Button *self) const;
    };
    Qul::Private::Binding<Button_3934977972_bindingFunctor, 0> font_font_binding;
    struct Button_1880257050_bindingFunctor {
        Qul::Private::String operator()(Button *self) const;
    };
    Qul::Private::Binding<Button_1880257050_bindingFunctor, 0> text__text_binding;
    struct Button_638361119_bindingFunctor {
        int operator()(Button *self) const;
    };
    Qul::Private::Binding<Button_638361119_bindingFunctor, 0> _implicitHeight_binding;
    struct Button_2791446706_bindingFunctor {
        int operator()(Button *self) const;
    };
    Qul::Private::Binding<Button_2791446706_bindingFunctor, 0> _implicitWidth_binding;
};

} // namespace QtQuick
} // namespace Controls
} // namespace StyleDefault
