// This code is auto-generated by Qul's qmltocpp tool from the file 'CheckBox.qml'
// WARNING! All changes made in this file will be lost!
#include "CheckBox.h"
#include <qul/private/graphicsdevice.h>
#include <qul/private/filecache.h>

extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_checkbox_2Ddisabled_13247221153793960132_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_checkbox_2Dpartially_2Dchecked_2Dpressed_11192065766233254474_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_checkbox_2Dpartially_2Dchecked_3384688200196511074_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_checkbox_2Dchecked_2Dpressed_2210782209603159047_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_checkbox_2Dchecked_3676362399952859206_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_checkbox_17080658918307490481_handle;
static const Qul::Private::String qulCurrentFileDir(".", 1);
namespace QtQuick {
namespace Controls {
namespace StyleDefault {
extern Qul::Private::Items::ItemBase *loaderItemAllocator(const Qul::Private::String &uri, const Qul::Private::String &currentFileDir);

} // namespace QtQuick
} // namespace Controls
} // namespace StyleDefault
namespace Qul { namespace Private {
Qul::Property<int> &translationIndexProperty_da39a3ee5e6b4b0d3255bfef95601890afd80709();
extern const uint32_t *qul_translation_offsets_14d0fb2ce8f4a1278957dff09426fb9da82d504d();
extern const uint8_t *qul_translations_14d0fb2ce8f4a1278957dff09426fb9da82d504d();
}}

namespace QtQuick {
namespace Controls {
namespace StyleDefault {

namespace {
#if defined(QUL_CC_IAR)
#pragma diag_suppress=Pe177 // declared but never referenced
#elif defined(QUL_CC_GNU)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-function"
#endif
static Qul::Property<int> &translationIndexProperty() { return Qul::Private::translationIndexProperty_da39a3ee5e6b4b0d3255bfef95601890afd80709(); }
static int translationIndex() { return translationIndexProperty().value(); }
static const char *qul_translation(int entry) {
    const size_t translationLanguageCount = 1;
    const uint32_t *offsets = Qul::Private::qul_translation_offsets_14d0fb2ce8f4a1278957dff09426fb9da82d504d();
    const uint8_t *translations = Qul::Private::qul_translations_14d0fb2ce8f4a1278957dff09426fb9da82d504d();
    return reinterpret_cast<const char *>(&translations[offsets[entry * translationLanguageCount + translationIndex()]]);
}
#if defined(QUL_CC_IAR)
#pragma diag_default=Pe177 // declared but never referenced
#elif defined(QUL_CC_GNU)
#pragma GCC diagnostic pop
#endif
}


int CheckBox::CheckBox_2598478316_bindingFunctor::operator()(CheckBox *self) const
{
    (void) self;
    int r2_1;
    QUL_DECL_UNUSED CheckBox * r2 = NULL;
    QUL_DECL_UNUSED Qul::Private::Items::ItemBase * r2__indicator = NULL;
    int r7__indicator_width;
    // implicitWidth: control.indicator ? control.indicator.width + control.spacing : 0
    // line 71  "CheckBox.qml"
    r2 = self;
    r2__indicator = r2->indicator.value();
    if (!r2__indicator) {
    goto label_0;};
    r2 = self;
    r2__indicator = r2->indicator.value();
    r2_1 = r2__indicator->width.value();
    r7__indicator_width = r2_1;
    r2 = self;
    r2_1 = r2->spacing.value();
    r2_1 = r7__indicator_width + r2_1;
    goto label_1;;
    {
    }
    label_0:;
    r2_1 = 0;
    label_1:;
    return r2_1;
    
}
int CheckBox::text__y_anchor_bindingFunctor::operator()(CheckBox *self) const {
        return int((int(self->row.height.value()) + 1)/2 - ((self->text_.height.value())/2.0));
}
Qul::PlatformInterface::Rgba32 CheckBox::CheckBox_2336064621_bindingFunctor::operator()(CheckBox *self) const
{
    (void) self;
    QUL_DECL_UNUSED Qul::PlatformInterface::Rgba32 r2__disabledTextColor;
    bool r2__enabled;
    QUL_DECL_UNUSED CheckBox * r2 = NULL;
    QUL_DECL_UNUSED  ::QtQuick::Controls::StyleDefault::DefaultStyle * r2_3 = NULL;
    // color: control.enabled ? DefaultStyle.textColor : DefaultStyle.disabledTextColor
    // line 77  "CheckBox.qml"
    r2 = self;
    r2__enabled = r2->enabled.value();
    if (!r2__enabled) goto label_0;;
    r2_3 = & ::QtQuick::Controls::StyleDefault::DefaultStyle ::instance();
    r2__disabledTextColor = r2_3->textColor.value();
    goto label_1;;
    label_0:;
    r2_3 = & ::QtQuick::Controls::StyleDefault::DefaultStyle ::instance();
    r2__disabledTextColor = r2_3->disabledTextColor.value();
    label_1:;
    return r2__disabledTextColor;
    
}
Qul::Private::FontPointer CheckBox::CheckBox_524833712_bindingFunctor::operator()(CheckBox *self) const
{
    (void) self;
    QUL_DECL_UNUSED CheckBox * r2 = NULL;
    QUL_DECL_UNUSED Qul::Private::FontPointer r2__font;
    // font: control.font
    // line 76  "CheckBox.qml"
    r2 = self;
    r2__font = r2->font.value();
    return r2__font;
    
}
Qul::Private::String CheckBox::CheckBox_2129819560_bindingFunctor::operator()(CheckBox *self) const
{
    (void) self;
    QUL_DECL_UNUSED Qul::Private::String r2__text;
    QUL_DECL_UNUSED CheckBox * r2 = NULL;
    // text: control.text
    // line 75  "CheckBox.qml"
    r2 = self;
    r2__text = r2->text.value();
    return r2__text;
    
}
Qul::SharedImage CheckBox::CheckBox_391678763_bindingFunctor::operator()(CheckBox *self) const
{
    (void) self;
    QUL_DECL_UNUSED Qul::Private::Builtins::GlobalQtObject::CheckState r8__checkState;
    bool r2_3;
    QUL_DECL_UNUSED Qul::Private::Builtins::GlobalQtObject::CheckState r2__PartiallyChecked;
    QUL_DECL_UNUSED Qul::Private::String r2_2;
    QUL_DECL_UNUSED CheckBox * r2 = NULL;
    QUL_DECL_UNUSED Qul::Private::Builtins::GlobalQtObject::CheckState r7__checkState;
    /*
    source: !control.enabled
    ? "qrc:/images/checkbox-disabled.png"
    : (control.checkState == Qt.PartiallyChecked
    */
    // line 53  "CheckBox.qml"
    r2 = self;
    r2_3 = r2->enabled.value();
    r2_3 = !r2_3;
    if (!r2_3) goto label_0;;
    r2_2 = Qul::Private::String(Qul::Private::ImageIdValue::create("qrc:/images/checkbox-disabled.png", qul_rasterBuffer_checkbox_2Ddisabled_13247221153793960132_handle), 33);
    {
    goto label_1;};
    label_0:;
    r2 = self;
    r2__PartiallyChecked = r2->checkState.value();
    r7__checkState = r2__PartiallyChecked;
    r2__PartiallyChecked = Qul::Private::Builtins::GlobalQtObject::PartiallyChecked;
    r2_3 = Qul::Private::testEqual(r7__checkState, r2__PartiallyChecked);
    if (!r2_3) goto label_2;;
    r2 = self;
    /*
    ? (control.down ? "qrc:/images/checkbox-partially-checked-pressed.png" : "qrc:/images/checkbox-partially-checked.png")
    : (control.checkState == Qt.Checked
    */
    // line 56  "CheckBox.qml"
    r2_3 = r2->down.value();
    if (!r2_3) goto label_3;;
    r2_2 = Qul::Private::String(Qul::Private::ImageIdValue::create("qrc:/images/checkbox-partially-checked-pressed.png", qul_rasterBuffer_checkbox_2Dpartially_2Dchecked_2Dpressed_11192065766233254474_handle), 50);
    goto label_4;;
    label_3:;
    r2_2 = Qul::Private::String(Qul::Private::ImageIdValue::create("qrc:/images/checkbox-partially-checked.png", qul_rasterBuffer_checkbox_2Dpartially_2Dchecked_3384688200196511074_handle), 42);
    label_4:;
    {
    goto label_1;};
    label_2:;
    r2 = self;
    r2__PartiallyChecked = r2->checkState.value();
    r8__checkState = r2__PartiallyChecked;
    r2__PartiallyChecked = Qul::Private::Builtins::GlobalQtObject::Checked;
    r2_3 = Qul::Private::testEqual(r8__checkState, r2__PartiallyChecked);
    if (!r2_3) goto label_5;;
    r2 = self;
    // ? (control.down ? "qrc:/images/checkbox-checked-pressed.png" : "qrc:/images/checkbox-checked.png")
    // line 58  "CheckBox.qml"
    r2_3 = r2->down.value();
    if (!r2_3) goto label_6;;
    r2_2 = Qul::Private::String(Qul::Private::ImageIdValue::create("qrc:/images/checkbox-checked-pressed.png", qul_rasterBuffer_checkbox_2Dchecked_2Dpressed_2210782209603159047_handle), 40);
    goto label_7;;
    label_6:;
    r2_2 = Qul::Private::String(Qul::Private::ImageIdValue::create("qrc:/images/checkbox-checked.png", qul_rasterBuffer_checkbox_2Dchecked_3676362399952859206_handle), 32);
    label_7:;
    {
    goto label_1;};
    label_5:;
    r2_2 = Qul::Private::String(Qul::Private::ImageIdValue::create("qrc:/images/checkbox.png", qul_rasterBuffer_checkbox_17080658918307490481_handle), 24);
    {
    }
    label_1:;
    // : "qrc:/images/checkbox.png"))
    // line 59  "CheckBox.qml"
    return Qul::Private::findImageForString(r2_2);
    
}
int CheckBox::CheckBox_2596551328_bindingFunctor::operator()(CheckBox *self) const
{
    (void) self;
    int r8__availableHeight;
    int r2_2;
    Qul::qreal r2_1;
    QUL_DECL_UNUSED CheckBox * r2 = NULL;
    int r9;
    int r7__topPadding;
    // y: control.topPadding + (control.availableHeight - height) / 2
    // line 52  "CheckBox.qml"
    r2 = self;
    r2_2 = r2->topPadding.value();
    r7__topPadding = r2_2;
    r2 = self;
    r2_2 = r2->availableHeight.value();
    r8__availableHeight = r2_2;
    r2_2 = self->image.height.value();
    r2_2 = r8__availableHeight - r2_2;
    r9 = r2_2;
    r2_2 = 2;
    r2_1 = Qul::qreal(r9) / r2_2;
    r2_1 = r7__topPadding + r2_1;
    return int(r2_1);
    
}
int CheckBox::CheckBox_3633115192_bindingFunctor::operator()(CheckBox *self) const
{
    (void) self;
    int r2__leftPadding;
    QUL_DECL_UNUSED CheckBox * r2 = NULL;
    // x: control.leftPadding
    // line 51  "CheckBox.qml"
    r2 = self;
    r2__leftPadding = r2->leftPadding.value();
    return r2__leftPadding;
    
}
int CheckBox::CheckBox_3560203182_bindingFunctor::operator()(CheckBox *self) const
{
    (void) self;
    QUL_DECL_UNUSED Qul::Private::Builtins::Math * r7 = NULL;
    int r13;
    int r16;
    int r2_1;
    Qul::qreal r2_3;
    QUL_DECL_UNUSED Qul::Private::Builtins::Math * r2 = NULL;
    QUL_DECL_UNUSED Qul::Private::Items::ItemBase * r2_2 = NULL;
    int r10;
    int r12_1;
    QUL_DECL_UNUSED Qul::Private::Builtins::Math * r12 = NULL;
    int r17;
    int r15;
    Qul::qreal r11;
    int r18;
    // implicitHeight: Math.max((background ? background.implicitHeight : 0) + topInset + bottomInset,
    // line 34  "CheckBox.qml"
    r2 = &Qul::Private::Builtins::Math ::instance();
    r7 = r2;
    r2_2 = self->background.value();
    if (!r2_2) goto label_0;;
    r2_2 = self->background.value();
    r2_1 = r2_2->itemExtraProperties->implicitHeight.value();
    goto label_1;;
    label_0:;
    r2_1 = 0;
    label_1:;
    r12_1 = r2_1;
    r2_1 = self->topInset.value();
    r2_1 = r12_1 + r2_1;
    r13 = r2_1;
    r2_1 = self->bottomInset.value();
    r2_1 = r13 + r2_1;
    r10 = r2_1;
    r2 = &Qul::Private::Builtins::Math ::instance();
    r12 = r2;
    // Math.max((contentItem ? contentItem.implicitHeight : 0) + topPadding + bottomPadding,
    // line 35  "CheckBox.qml"
    r2_2 = self->contentItem.value();
    if (!r2_2) goto label_2;;
    r2_2 = self->contentItem.value();
    r2_1 = r2_2->itemExtraProperties->implicitHeight.value();
    goto label_3;;
    label_2:;
    r2_1 = 0;
    label_3:;
    r17 = r2_1;
    r2_1 = self->topPadding.value();
    r2_1 = r17 + r2_1;
    r18 = r2_1;
    r2_1 = self->bottomPadding.value();
    r2_1 = r18 + r2_1;
    r15 = r2_1;
    // (indicator ? indicator.implicitHeight : 0) + topPadding + bottomPadding))
    // line 36  "CheckBox.qml"
    r2_2 = self->indicator.value();
    if (!r2_2) goto label_4;;
    r2_2 = self->indicator.value();
    r2_1 = r2_2->itemExtraProperties->implicitHeight.value();
    goto label_5;;
    label_4:;
    r2_1 = 0;
    label_5:;
    r17 = r2_1;
    r2_1 = self->topPadding.value();
    r2_1 = r17 + r2_1;
    r18 = r2_1;
    r2_1 = self->bottomPadding.value();
    r2_1 = r18 + r2_1;
    r16 = r2_1;
    r2_3 = r12->max(r15, r16);
    r11 = r2_3;
    r2_3 = r7->max(r10, r11);
    return int(r2_3);
    
}
int CheckBox::CheckBox_2791446706_bindingFunctor::operator()(CheckBox *self) const
{
    (void) self;
    int r2_2;
    Qul::qreal r2_1;
    QUL_DECL_UNUSED Qul::Private::Builtins::Math * r2 = NULL;
    QUL_DECL_UNUSED Qul::Private::Items::ItemBase * r2_3 = NULL;
    int r10;
    int r12;
    int r11;
    QUL_DECL_UNUSED Qul::Private::Builtins::Math * r7 = NULL;
    int r13;
    // implicitWidth: Math.max((background ? background.implicitWidth : 0) + leftInset + rightInset,
    // line 28  "CheckBox.qml"
    r2 = &Qul::Private::Builtins::Math ::instance();
    r7 = r2;
    r2_3 = self->background.value();
    if (!r2_3) goto label_0;;
    r2_3 = self->background.value();
    r2_2 = r2_3->itemExtraProperties->implicitWidth.value();
    goto label_1;;
    label_0:;
    r2_2 = 0;
    label_1:;
    r12 = r2_2;
    r2_2 = self->leftInset.value();
    r2_2 = r12 + r2_2;
    r13 = r2_2;
    r2_2 = self->rightInset.value();
    r2_2 = r13 + r2_2;
    r10 = r2_2;
    // (contentItem ? contentItem.implicitWidth : 0) + leftPadding + rightPadding)
    // line 29  "CheckBox.qml"
    r2_3 = self->contentItem.value();
    if (!r2_3) goto label_2;;
    r2_3 = self->contentItem.value();
    r2_2 = r2_3->itemExtraProperties->implicitWidth.value();
    goto label_3;;
    label_2:;
    r2_2 = 0;
    label_3:;
    r12 = r2_2;
    r2_2 = self->leftPadding.value();
    r2_2 = r12 + r2_2;
    r13 = r2_2;
    r2_2 = self->rightPadding.value();
    r2_2 = r13 + r2_2;
    r11 = r2_2;
    r2_1 = r7->max(r10, r11);
    return int(r2_1);
    
}

CheckBox::CheckBox()

    : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Controls::Templates::CheckBox  >(this)
    , item__2_implicitWidth_binding(CheckBox_2598478316_bindingFunctor())
    , text__y_anchor_binding(text__y_anchor_bindingFunctor())
    , text__color_binding(CheckBox_2336064621_bindingFunctor())
    , font_font_binding(CheckBox_524833712_bindingFunctor())
    , text__text_binding(CheckBox_2129819560_bindingFunctor())
    , image_source_binding(CheckBox_391678763_bindingFunctor())
    , image_y_binding(CheckBox_2596551328_bindingFunctor())
    , image_x_binding(CheckBox_3633115192_bindingFunctor())
    , _implicitHeight_binding(CheckBox_3560203182_bindingFunctor())
    , _implicitWidth_binding(CheckBox_2791446706_bindingFunctor())
{
    // Item {
    // line 70  "CheckBox.qml"
    appendChild(&this->row, &item__2);
    item__2_implicitWidth_binding.init<CheckBox, &CheckBox::item__2_implicitWidth_binding>(item__2.itemExtraProperties->implicitWidth);
    // implicitWidth: control.indicator ? control.indicator.width + control.spacing : 0
    // line 71  "CheckBox.qml"
    item__2.itemExtraProperties->implicitWidth.setBinding (&item__2_implicitWidth_binding);
    // Text {
    // line 74  "CheckBox.qml"
    appendChild(&this->row, &text_);
    text__y_anchor_binding.init<CheckBox, &CheckBox::text__y_anchor_binding>(text_.y);
    text_.y.setBinding(&text__y_anchor_binding);
    text__color_binding.init<CheckBox, &CheckBox::text__color_binding>(text_.color);
    // color: control.enabled ? DefaultStyle.textColor : DefaultStyle.disabledTextColor
    // line 77  "CheckBox.qml"
    text_.color.setBinding (&text__color_binding);
    font_font_binding.init<CheckBox, &CheckBox::font_font_binding>(text_.font);
    // font: control.font
    // line 76  "CheckBox.qml"
    text_.font.setBinding (&font_font_binding);
    text__text_binding.init<CheckBox, &CheckBox::text__text_binding>(text_.text);
    // text: control.text
    // line 75  "CheckBox.qml"
    text_.text.setBinding (&text__text_binding);
    // contentItem: Row {
    // line 69  "CheckBox.qml"
    contentItem.setValue(&row);
    // implicitHeight: 42
    // line 65  "CheckBox.qml"
    item_.itemExtraProperties->implicitHeight.setValue(42);
    // implicitWidth: 100
    // line 64  "CheckBox.qml"
    item_.itemExtraProperties->implicitWidth.setValue(100);
    // background: Item {
    // line 63  "CheckBox.qml"
    background.setValue(&item_);
    image_source_binding.init<CheckBox, &CheckBox::image_source_binding>(image.source);
    // source: !control.enabled
    // line 53  "CheckBox.qml"
    image.source.setBinding (&image_source_binding);
    image_y_binding.init<CheckBox, &CheckBox::image_y_binding>(image.y);
    // y: control.topPadding + (control.availableHeight - height) / 2
    // line 52  "CheckBox.qml"
    image.y.setBinding (&image_y_binding);
    image_x_binding.init<CheckBox, &CheckBox::image_x_binding>(image.x);
    // x: control.leftPadding
    // line 51  "CheckBox.qml"
    image.x.setBinding (&image_x_binding);
    // indicator: Image {
    // line 50  "CheckBox.qml"
    indicator.setValue(&image);
    // spacing: 10
    // line 48  "CheckBox.qml"
    spacing.setValue(10);
    // bottomInset: DefaultStyle.inset
    // line 46  "CheckBox.qml"
    bottomInset.setValue(5);
    // rightInset: DefaultStyle.inset
    // line 45  "CheckBox.qml"
    rightInset.setValue(5);
    // topInset: DefaultStyle.inset
    // line 44  "CheckBox.qml"
    topInset.setValue(5);
    // leftInset: DefaultStyle.inset
    // line 43  "CheckBox.qml"
    leftInset.setValue(5);
    // bottomPadding: DefaultStyle.padding
    // line 41  "CheckBox.qml"
    bottomPadding.setValue(5);
    // topPadding: DefaultStyle.padding
    // line 40  "CheckBox.qml"
    topPadding.setValue(5);
    // rightPadding: DefaultStyle.padding
    // line 39  "CheckBox.qml"
    rightPadding.setValue(5);
    // leftPadding: DefaultStyle.padding
    // line 38  "CheckBox.qml"
    leftPadding.setValue(5);
    _implicitHeight_binding.init<CheckBox, &CheckBox::_implicitHeight_binding>(itemExtraProperties->implicitHeight);
    // implicitHeight: Math.max((background ? background.implicitHeight : 0) + topInset + bottomInset,
    // line 34  "CheckBox.qml"
    itemExtraProperties->implicitHeight.setBinding (&_implicitHeight_binding);
    _implicitWidth_binding.init<CheckBox, &CheckBox::_implicitWidth_binding>(itemExtraProperties->implicitWidth);
    // implicitWidth: Math.max((background ? background.implicitWidth : 0) + leftInset + rightInset,
    // line 28  "CheckBox.qml"
    itemExtraProperties->implicitWidth.setBinding (&_implicitWidth_binding);
}

} // namespace QtQuick
} // namespace Controls
} // namespace StyleDefault
