// This code is auto-generated by Qul's qmltocpp tool from the file 'CheckBox.qml'
// WARNING! All changes made in this file will be lost!
// NOTE: This generated API is to be considered implementation detail for Qul.
//       It may change from version to version and should not be relied upon.
#pragma once
#include "DefaultStyle.h"
#include <platforminterface/log.h>
#include <qul/image.h>
#include <qul/private/builtins.h>
#include <qul/private/controls/checkboxtemplate.h>
#include <qul/private/file.h>
#include <qul/private/items.h>
#include <qul/private/items/item.h>
#include <qul/private/items/text.h>
#include <qul/private/qulrcc_lookup.h>
#include <qul/private/unicodestring.h>
#include <qul/signal.h>

namespace QtQuick {
namespace Controls {
namespace StyleDefault {

struct CheckBox : Qul::Private::Controls::Templates::CheckBox , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Controls::Templates::CheckBox  > {
    CheckBox();


    Qul::Property<Qul::Private::String> state;
    struct item__2_Item : Qul::Private::Items::Item , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Item  > {
        item__2_Item()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Item  >(this)
        {}
    } item__2;
    typedef Qul::Private::Items::TextLight  text__Text;
    text__Text text_;
    struct row_Row : Qul::Private::Items::Row , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Row  > {
        row_Row()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Row  >(this)
        {}
    } row;
    struct item__Item : Qul::Private::Items::Item , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Item  > {
        item__Item()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Item  >(this)
        {}
    } item_;
    struct image_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        image_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } image;
    struct CheckBox_2598478316_bindingFunctor {
        int operator()(CheckBox *self) const;
    };
    Qul::Private::Binding<CheckBox_2598478316_bindingFunctor, 0> item__2_implicitWidth_binding;
    struct text__y_anchor_bindingFunctor {
    int operator()(CheckBox *self) const;
};
    Qul::Private::Binding<text__y_anchor_bindingFunctor, 2> text__y_anchor_binding;
    struct CheckBox_2336064621_bindingFunctor {
        Qul::PlatformInterface::Rgba32 operator()(CheckBox *self) const;
    };
    Qul::Private::Binding<CheckBox_2336064621_bindingFunctor, 0> text__color_binding;
    struct CheckBox_524833712_bindingFunctor {
        Qul::Private::FontPointer operator()(CheckBox *self) const;
    };
    Qul::Private::Binding<CheckBox_524833712_bindingFunctor, 0> font_font_binding;
    struct CheckBox_2129819560_bindingFunctor {
        Qul::Private::String operator()(CheckBox *self) const;
    };
    Qul::Private::Binding<CheckBox_2129819560_bindingFunctor, 0> text__text_binding;
    struct CheckBox_391678763_bindingFunctor {
        Qul::SharedImage operator()(CheckBox *self) const;
    };
    Qul::Private::Binding<CheckBox_391678763_bindingFunctor, 0> image_source_binding;
    struct CheckBox_2596551328_bindingFunctor {
        int operator()(CheckBox *self) const;
    };
    Qul::Private::Binding<CheckBox_2596551328_bindingFunctor, 0> image_y_binding;
    struct CheckBox_3633115192_bindingFunctor {
        int operator()(CheckBox *self) const;
    };
    Qul::Private::Binding<CheckBox_3633115192_bindingFunctor, 0> image_x_binding;
    struct CheckBox_3560203182_bindingFunctor {
        int operator()(CheckBox *self) const;
    };
    Qul::Private::Binding<CheckBox_3560203182_bindingFunctor, 0> _implicitHeight_binding;
    struct CheckBox_2791446706_bindingFunctor {
        int operator()(CheckBox *self) const;
    };
    Qul::Private::Binding<CheckBox_2791446706_bindingFunctor, 0> _implicitWidth_binding;
};

} // namespace QtQuick
} // namespace Controls
} // namespace StyleDefault
