// This code is auto-generated by Qul's qmltocpp tool from the file 'DefaultStyle.qml'
// WARNING! All changes made in this file will be lost!
// NOTE: This generated API is to be considered implementation detail for Qul.
//       It may change from version to version and should not be relied upon.
#pragma once
#include <platforminterface/log.h>
#include <qul/image.h>
#include <qul/private/file.h>
#include <qul/private/items.h>
#include <qul/private/qulrcc_lookup.h>
#include <qul/private/unicodestring.h>
#include <qul/signal.h>
namespace QtQuick {
namespace Controls {
namespace StyleDefault {

struct DefaultStyle : Qul::Object  {
    DefaultStyle();
    static DefaultStyle &instance();


    Qul::Property<int> inset;
    Qul::Property<int> padding;
    Qul::Property<Qul::PlatformInterface::Rgba32> textColor;
    Qul::Property<Qul::PlatformInterface::Rgba32> disabledTextColor;
};

} // namespace QtQuick
} // namespace Controls
} // namespace StyleDefault
