// This code is auto-generated by Qul's qmltocpp tool from the file 'DefaultStyle.qml'
// WARNING! All changes made in this file will be lost!
#include "DefaultStyle.h"
#include <qul/private/graphicsdevice.h>
#include <qul/private/filecache.h>

static const Qul::Private::String qulCurrentFileDir(".", 1);
namespace QtQuick {
namespace Controls {
namespace StyleDefault {
extern Qul::Private::Items::ItemBase *loaderItemAllocator(const Qul::Private::String &uri, const Qul::Private::String &currentFileDir);

} // namespace QtQuick
} // namespace Controls
} // namespace StyleDefault
namespace Qul { namespace Private {
Qul::Property<int> &translationIndexProperty_da39a3ee5e6b4b0d3255bfef95601890afd80709();
extern const uint32_t *qul_translation_offsets_2e4563ca0a4fe31a21ddbf995058f99d27bf4fdf();
extern const uint8_t *qul_translations_2e4563ca0a4fe31a21ddbf995058f99d27bf4fdf();
}}

namespace QtQuick {
namespace Controls {
namespace StyleDefault {

namespace {
#if defined(QUL_CC_IAR)
#pragma diag_suppress=Pe177 // declared but never referenced
#elif defined(QUL_CC_GNU)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-function"
#endif
static Qul::Property<int> &translationIndexProperty() { return Qul::Private::translationIndexProperty_da39a3ee5e6b4b0d3255bfef95601890afd80709(); }
static int translationIndex() { return translationIndexProperty().value(); }
static const char *qul_translation(int entry) {
    const size_t translationLanguageCount = 1;
    const uint32_t *offsets = Qul::Private::qul_translation_offsets_2e4563ca0a4fe31a21ddbf995058f99d27bf4fdf();
    const uint8_t *translations = Qul::Private::qul_translations_2e4563ca0a4fe31a21ddbf995058f99d27bf4fdf();
    return reinterpret_cast<const char *>(&translations[offsets[entry * translationLanguageCount + translationIndex()]]);
}
#if defined(QUL_CC_IAR)
#pragma diag_default=Pe177 // declared but never referenced
#elif defined(QUL_CC_GNU)
#pragma GCC diagnostic pop
#endif
}



DefaultStyle::DefaultStyle()

{
    // readonly property color disabledTextColor: "#c4c9cb"
    // line 27  "DefaultStyle.qml"
    disabledTextColor.setValue(0xffc4c9cb);
    // readonly property color textColor: "#3d464d"
    // line 26  "DefaultStyle.qml"
    textColor.setValue(0xff3d464d);
    // readonly property int padding: 5
    // line 25  "DefaultStyle.qml"
    padding.setValue(5);
    // readonly property int inset: 5
    // line 24  "DefaultStyle.qml"
    inset.setValue(5);
}
DefaultStyle &DefaultStyle::instance()
{
    static DefaultStyle instance;
    return instance;
}

} // namespace QtQuick
} // namespace Controls
} // namespace StyleDefault
