// This code is auto-generated by Qul's qmltocpp tool from the file 'Dial.qml'
// WARNING! All changes made in this file will be lost!
#include "Dial.h"
#include <qul/private/graphicsdevice.h>
#include <qul/private/filecache.h>

extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_dial_2Dbackground_2Ddisabled_15345896986866248576_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_dial_2Dbackground_3190004907980333205_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_dial_2Dprogress_14694211536943410449_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_slider_2Dhandle_4014514759752923839_handle;
static const Qul::Private::String qulCurrentFileDir(".", 1);
namespace QtQuick {
namespace Controls {
namespace StyleDefault {
extern Qul::Private::Items::ItemBase *loaderItemAllocator(const Qul::Private::String &uri, const Qul::Private::String &currentFileDir);

} // namespace QtQuick
} // namespace Controls
} // namespace StyleDefault
namespace Qul { namespace Private {
Qul::Property<int> &translationIndexProperty_da39a3ee5e6b4b0d3255bfef95601890afd80709();
extern const uint32_t *qul_translation_offsets_4ae74f6997f636296933f9c4c859922cb2e0c16d();
extern const uint8_t *qul_translations_4ae74f6997f636296933f9c4c859922cb2e0c16d();
}}

namespace QtQuick {
namespace Controls {
namespace StyleDefault {

namespace {
#if defined(QUL_CC_IAR)
#pragma diag_suppress=Pe177 // declared but never referenced
#elif defined(QUL_CC_GNU)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-function"
#endif
static Qul::Property<int> &translationIndexProperty() { return Qul::Private::translationIndexProperty_da39a3ee5e6b4b0d3255bfef95601890afd80709(); }
static int translationIndex() { return translationIndexProperty().value(); }
static const char *qul_translation(int entry) {
    const size_t translationLanguageCount = 1;
    const uint32_t *offsets = Qul::Private::qul_translation_offsets_4ae74f6997f636296933f9c4c859922cb2e0c16d();
    const uint8_t *translations = Qul::Private::qul_translations_4ae74f6997f636296933f9c4c859922cb2e0c16d();
    return reinterpret_cast<const char *>(&translations[offsets[entry * translationLanguageCount + translationIndex()]]);
}
#if defined(QUL_CC_IAR)
#pragma diag_default=Pe177 // declared but never referenced
#elif defined(QUL_CC_GNU)
#pragma GCC diagnostic pop
#endif
}


int Dial::item_::item__1481434427_bindingFunctor::operator()(item_ *self) const
{
    (void) self;
    int r8__height;
    int r2_1;
    bool r2_3;
    QUL_DECL_UNUSED backgroundImg_Image * r2_2 = NULL;
    Qul::qreal r2;
    Qul::qreal r9;
    int r7;
    // switch (index) {
    // line 103  "Dial.qml"
    r2_1 = self->attached_index.value();
    r7 = r2_1;
    r2_1 = 0;
    r2_3 = r7 == r2_1;
    if (r2_3) goto label_0;;
    r2_1 = 1;
    r2_3 = r7 == r2_1;
    if (r2_3) {
    goto label_1;};
    r2_1 = 2;
    r2_3 = r7 == r2_1;
    if (r2_3) {
    goto label_2;};
    r2_1 = 3;
    r2_3 = r7 == r2_1;
    if (r2_3) goto label_3;;
    {
    goto label_4;};
    label_0:;
    // case 0: return backgroundImg.height - height;
    // line 104  "Dial.qml"
    r2_2 = &self->parentScope->backgroundImg;
    r2_1 = r2_2->height.value();
    r8__height = r2_1;
    r2_1 = self->height.value();
    r2_1 = r8__height - r2_1;
    return r2_1;
    {
    }
    label_1:;
    // case 1: return backgroundImg.height /2 - height;
    // line 105  "Dial.qml"
    r2_2 = &self->parentScope->backgroundImg;
    r2_1 = r2_2->height.value();
    r8__height = r2_1;
    r2_1 = 2;
    r2 = Qul::qreal(r8__height) / r2_1;
    r9 = r2;
    r2_1 = self->height.value();
    r2 = r9 - r2_1;
    return int(r2);
    {
    }
    label_2:;
    // case 2: return 0;
    // line 106  "Dial.qml"
    r2_1 = 0;
    return r2_1;
    label_3:;
    /*
    case 3: return backgroundImg.height /2;
    }
    */
    // line 107  "Dial.qml"
    r2_2 = &self->parentScope->backgroundImg;
    r2_1 = r2_2->height.value();
    r8__height = r2_1;
    r2_1 = 2;
    r2 = Qul::qreal(r8__height) / r2_1;
    return int(r2);
    {
    }
    label_4:;
    // }
    // line 109  "Dial.qml"
    return int();
    
}
int Dial::item_::item__1797471572_bindingFunctor::operator()(item_ *self) const
{
    (void) self;
    Qul::qreal r9;
    int r2_1;
    bool r2_2;
    QUL_DECL_UNUSED backgroundImg_Image * r2 = NULL;
    QUL_DECL_UNUSED handleImg_Image * r2_5 = NULL;
    Qul::qreal r2_3;
    QUL_DECL_UNUSED Dial * r2_4 = NULL;
    int r10__y;
    Qul::qreal r10__angle;
    int r12;
    int r11;
    Qul::qreal r11_1;
    bool r8;
    Qul::qreal r7;
    Qul::qreal r13;
    // var quadrantSize = backgroundImg.height/2;
    // line 90  "Dial.qml"
    r2 = &self->parentScope->backgroundImg;
    r2_1 = r2->height.value();
    r10__y = r2_1;
    r2_1 = 2;
    r2_3 = Qul::qreal(r10__y) / r2_1;
    r9 = r2_3;
    // if (control.angle < -180 + index*90) return 0;
    // line 91  "Dial.qml"
    r2_4 = self->parentScope;
    r2_3 = r2_4->angle.value();
    r10__angle = r2_3;
    r11 = -180;
    r2_1 = self->attached_index.value();
    r12 = r2_1;
    r2_1 = 90;
    r2_1 = r12 * r2_1;
    r2_1 = r11 + r2_1;
    r2_2 = r10__angle < r2_1;
    if (!r2_2) goto label_0;;
    r2_1 = 0;
    return r2_1;
    label_0:;
    // if (control.angle > -90 + index*90) return quadrantSize;
    // line 92  "Dial.qml"
    r2_4 = self->parentScope;
    r2_3 = r2_4->angle.value();
    r10__angle = r2_3;
    r11 = -90;
    r2_1 = self->attached_index.value();
    r12 = r2_1;
    r2_1 = 90;
    r2_1 = r12 * r2_1;
    r2_1 = r11 + r2_1;
    r2_2 = r10__angle > r2_1;
    if (!r2_2) goto label_1;;
    r2_3 = r9;
    return int(r2_3);
    label_1:;
    // var low = control.angle + 180 - index*90 < 45
    // line 93  "Dial.qml"
    r2_4 = self->parentScope;
    r2_3 = r2_4->angle.value();
    r10__angle = r2_3;
    r2_1 = 180;
    r2_3 = r10__angle + r2_1;
    r11_1 = r2_3;
    r2_1 = self->attached_index.value();
    r12 = r2_1;
    r2_1 = 90;
    r2_1 = r12 * r2_1;
    r2_3 = r11_1 - r2_1;
    r13 = r2_3;
    r2_1 = 45;
    r2_2 = r13 < r2_1;
    r8 = r2_2;
    // var handlePos = (handleImg.y - backgroundImg.y + handleImg.height/2);
    // line 94  "Dial.qml"
    r2_5 = &self->parentScope->handleImg;
    r2_1 = r2_5->y.value();
    r10__y = r2_1;
    r2 = &self->parentScope->backgroundImg;
    r2_1 = r2->y.value();
    r2_1 = r10__y - r2_1;
    r11 = r2_1;
    r2_5 = &self->parentScope->handleImg;
    r2_1 = r2_5->height.value();
    r12 = r2_1;
    r2_1 = 2;
    r2_3 = Qul::qreal(r12) / r2_1;
    r2_3 = r11 + r2_3;
    r7 = r2_3;
    // switch (index) {
    // line 95  "Dial.qml"
    r2_1 = self->attached_index.value();
    r10__y = r2_1;
    r2_1 = 0;
    r2_2 = r10__y == r2_1;
    if (r2_2) goto label_2;;
    r2_1 = 1;
    r2_2 = r10__y == r2_1;
    if (r2_2) {
    r11_1 = r11;
    goto label_3;};
    r2_1 = 2;
    r2_2 = r10__y == r2_1;
    if (r2_2) {
    r11_1 = r11;
    goto label_4;};
    r2_1 = 3;
    r2_2 = r10__y == r2_1;
    if (r2_2) {
    r11_1 = r11;
    goto label_5;};
    {
    r11_1 = r11;
    goto label_6;};
    label_2:;
    // case 0: return low ? quadrantSize : quadrantSize*2 - handlePos;
    // line 96  "Dial.qml"
    r2_2 = r8;
    if (!r2_2) goto label_7;;
    r2_3 = r9;
    {
    r11_1 = r11;
    goto label_8;};
    label_7:;
    r2_1 = 2;
    r2_3 = r9 * r2_1;
    r11_1 = r2_3;
    r2_3 = r7;
    r2_3 = r11_1 - r2_3;
    {
    }
    label_8:;
    return int(r2_3);
    {
    }
    label_3:;
    // case 1: return low ? quadrantSize - handlePos : quadrantSize;
    // line 97  "Dial.qml"
    r2_2 = r8;
    if (!r2_2) goto label_9;;
    r2_3 = r7;
    r2_3 = r9 - r2_3;
    goto label_10;;
    label_9:;
    r2_3 = r9;
    label_10:;
    return int(r2_3);
    {
    }
    label_4:;
    // case 2: return low ? quadrantSize : handlePos;
    // line 98  "Dial.qml"
    r2_2 = r8;
    if (!r2_2) goto label_11;;
    r2_3 = r9;
    goto label_12;;
    label_11:;
    r2_3 = r7;
    label_12:;
    return int(r2_3);
    {
    }
    label_5:;
    /*
    case 3: return low ? handlePos - quadrantSize : quadrantSize;
    }
    */
    // line 99  "Dial.qml"
    r2_2 = r8;
    if (!r2_2) goto label_13;;
    r2_3 = r9;
    r2_3 = r7 - r2_3;
    goto label_14;;
    label_13:;
    r2_3 = r9;
    label_14:;
    return int(r2_3);
    {
    }
    label_6:;
    // }
    // line 101  "Dial.qml"
    return int();
    
}
int Dial::item_::item__3592665794_bindingFunctor::operator()(item_ *self) const
{
    (void) self;
    int r8__width;
    int r2;
    bool r2_2;
    QUL_DECL_UNUSED backgroundImg_Image * r2_1 = NULL;
    Qul::qreal r2_3;
    Qul::qreal r9;
    int r7;
    // switch (index) {
    // line 81  "Dial.qml"
    r2 = self->attached_index.value();
    r7 = r2;
    r2 = 0;
    r2_2 = r7 == r2;
    if (r2_2) goto label_0;;
    r2 = 1;
    r2_2 = r7 == r2;
    if (r2_2) {
    goto label_1;};
    r2 = 2;
    r2_2 = r7 == r2;
    if (r2_2) goto label_2;;
    r2 = 3;
    r2_2 = r7 == r2;
    if (r2_2) {
    goto label_3;};
    {
    goto label_4;};
    label_0:;
    // case 0: return backgroundImg.width/2 - width;
    // line 82  "Dial.qml"
    r2_1 = &self->parentScope->backgroundImg;
    r2 = r2_1->width.value();
    r8__width = r2;
    r2 = 2;
    r2_3 = Qul::qreal(r8__width) / r2;
    r9 = r2_3;
    r2 = self->width.value();
    r2_3 = r9 - r2;
    return int(r2_3);
    {
    }
    label_1:;
    // case 1: return 0;
    // line 83  "Dial.qml"
    r2 = 0;
    return r2;
    label_2:;
    // case 2: return backgroundImg.width/2;
    // line 84  "Dial.qml"
    r2_1 = &self->parentScope->backgroundImg;
    r2 = r2_1->width.value();
    r8__width = r2;
    r2 = 2;
    r2_3 = Qul::qreal(r8__width) / r2;
    return int(r2_3);
    {
    }
    label_3:;
    /*
    case 3: return backgroundImg.width - width;
    }
    */
    // line 85  "Dial.qml"
    r2_1 = &self->parentScope->backgroundImg;
    r2 = r2_1->width.value();
    r8__width = r2;
    r2 = self->width.value();
    r2 = r8__width - r2;
    return r2;
    {
    }
    label_4:;
    // }
    // line 87  "Dial.qml"
    return int();
    
}
int Dial::item_::item__3770268640_bindingFunctor::operator()(item_ *self) const
{
    (void) self;
    Qul::qreal r9;
    int r2_1;
    bool r2_2;
    QUL_DECL_UNUSED backgroundImg_Image * r2 = NULL;
    QUL_DECL_UNUSED handleImg_Image * r2_5 = NULL;
    Qul::qreal r2_3;
    QUL_DECL_UNUSED Dial * r2_4 = NULL;
    int r10__x;
    Qul::qreal r10__angle;
    int r12;
    int r11;
    Qul::qreal r11_1;
    bool r8;
    Qul::qreal r7;
    Qul::qreal r13;
    // var quadrantSize = backgroundImg.width/2;
    // line 68  "Dial.qml"
    r2 = &self->parentScope->backgroundImg;
    r2_1 = r2->width.value();
    r10__x = r2_1;
    r2_1 = 2;
    r2_3 = Qul::qreal(r10__x) / r2_1;
    r9 = r2_3;
    // if (control.angle < -180 + index*90) return 0;
    // line 69  "Dial.qml"
    r2_4 = self->parentScope;
    r2_3 = r2_4->angle.value();
    r10__angle = r2_3;
    r11 = -180;
    r2_1 = self->attached_index.value();
    r12 = r2_1;
    r2_1 = 90;
    r2_1 = r12 * r2_1;
    r2_1 = r11 + r2_1;
    r2_2 = r10__angle < r2_1;
    if (!r2_2) goto label_0;;
    r2_1 = 0;
    return r2_1;
    label_0:;
    // if (control.angle > -90 + index*90) return quadrantSize;
    // line 70  "Dial.qml"
    r2_4 = self->parentScope;
    r2_3 = r2_4->angle.value();
    r10__angle = r2_3;
    r11 = -90;
    r2_1 = self->attached_index.value();
    r12 = r2_1;
    r2_1 = 90;
    r2_1 = r12 * r2_1;
    r2_1 = r11 + r2_1;
    r2_2 = r10__angle > r2_1;
    if (!r2_2) goto label_1;;
    r2_3 = r9;
    return int(r2_3);
    label_1:;
    // var low = control.angle + 180 - index*90 < 45
    // line 71  "Dial.qml"
    r2_4 = self->parentScope;
    r2_3 = r2_4->angle.value();
    r10__angle = r2_3;
    r2_1 = 180;
    r2_3 = r10__angle + r2_1;
    r11_1 = r2_3;
    r2_1 = self->attached_index.value();
    r12 = r2_1;
    r2_1 = 90;
    r2_1 = r12 * r2_1;
    r2_3 = r11_1 - r2_1;
    r13 = r2_3;
    r2_1 = 45;
    r2_2 = r13 < r2_1;
    r8 = r2_2;
    // var handlePos = (handleImg.x - backgroundImg.x + handleImg.width/2);
    // line 72  "Dial.qml"
    r2_5 = &self->parentScope->handleImg;
    r2_1 = r2_5->x.value();
    r10__x = r2_1;
    r2 = &self->parentScope->backgroundImg;
    r2_1 = r2->x.value();
    r2_1 = r10__x - r2_1;
    r11 = r2_1;
    r2_5 = &self->parentScope->handleImg;
    r2_1 = r2_5->width.value();
    r12 = r2_1;
    r2_1 = 2;
    r2_3 = Qul::qreal(r12) / r2_1;
    r2_3 = r11 + r2_3;
    r7 = r2_3;
    // switch (index) {
    // line 73  "Dial.qml"
    r2_1 = self->attached_index.value();
    r10__x = r2_1;
    r2_1 = 0;
    r2_2 = r10__x == r2_1;
    if (r2_2) goto label_2;;
    r2_1 = 1;
    r2_2 = r10__x == r2_1;
    if (r2_2) goto label_3;;
    r2_1 = 2;
    r2_2 = r10__x == r2_1;
    if (r2_2) goto label_4;;
    r2_1 = 3;
    r2_2 = r10__x == r2_1;
    if (r2_2) goto label_5;;
    {
    r11_1 = r11;
    goto label_6;};
    label_2:;
    // case 0: return low ? quadrantSize - handlePos : quadrantSize;
    // line 74  "Dial.qml"
    r2_2 = r8;
    if (!r2_2) goto label_7;;
    r2_3 = r7;
    r2_3 = r9 - r2_3;
    goto label_8;;
    label_7:;
    r2_3 = r9;
    label_8:;
    return int(r2_3);
    label_3:;
    // case 1: return low ? quadrantSize : handlePos;
    // line 75  "Dial.qml"
    r2_2 = r8;
    if (!r2_2) goto label_9;;
    r2_3 = r9;
    goto label_10;;
    label_9:;
    r2_3 = r7;
    label_10:;
    return int(r2_3);
    label_4:;
    // case 2: return low ? handlePos - quadrantSize : quadrantSize;
    // line 76  "Dial.qml"
    r2_2 = r8;
    if (!r2_2) goto label_11;;
    r2_3 = r9;
    r2_3 = r7 - r2_3;
    goto label_12;;
    label_11:;
    r2_3 = r9;
    label_12:;
    return int(r2_3);
    label_5:;
    /*
    case 3: return low ? quadrantSize : quadrantSize*2 - handlePos;
    }
    */
    // line 77  "Dial.qml"
    r2_2 = r8;
    if (!r2_2) goto label_13;;
    r2_3 = r9;
    {
    r11_1 = r11;
    goto label_14;};
    label_13:;
    r2_1 = 2;
    r2_3 = r9 * r2_1;
    r11_1 = r2_3;
    r2_3 = r7;
    r2_3 = r11_1 - r2_3;
    {
    }
    label_14:;
    return int(r2_3);
    {
    }
    label_6:;
    // }
    // line 79  "Dial.qml"
    return int();
    
}
bool Dial::item_::item__3347951558_bindingFunctor::operator()(item_ *self) const
{
    (void) self;
    bool r2__enabled;
    QUL_DECL_UNUSED Dial * r2 = NULL;
    // visible: control.enabled
    // line 66  "Dial.qml"
    r2 = self->parentScope;
    r2__enabled = r2->enabled.value();
    return r2__enabled;
    
}
int Dial::item_::item__781781174_bindingFunctor::operator()(item_ *self) const
{
    (void) self;
    int r2__height;
    QUL_DECL_UNUSED backgroundImg_Image * r2 = NULL;
    // height: backgroundImg.height
    // line 116  "Dial.qml"
    r2 = &self->parentScope->backgroundImg;
    r2__height = r2->height.value();
    return r2__height;
    
}
int Dial::item_::item__2959489308_bindingFunctor::operator()(item_ *self) const
{
    (void) self;
    int r2__width;
    QUL_DECL_UNUSED backgroundImg_Image * r2 = NULL;
    // width: backgroundImg.width
    // line 115  "Dial.qml"
    r2 = &self->parentScope->backgroundImg;
    r2__width = r2->width.value();
    return r2__width;
    
}
int Dial::item_::item__3059855150_bindingFunctor::operator()(item_ *self) const
{
    (void) self;
    int r2__y;
    QUL_DECL_UNUSED item_* r2 = NULL;
    // y: -parent.y
    // line 114  "Dial.qml"
    r2 = self->image.parent<item_>();
    r2__y = r2->y.value();
    r2__y=-r2__y;
    return r2__y;
    
}
int Dial::item_::item__2022471783_bindingFunctor::operator()(item_ *self) const
{
    (void) self;
    int r2__x;
    QUL_DECL_UNUSED item_* r2 = NULL;
    // x: -parent.x
    // line 113  "Dial.qml"
    r2 = self->image.parent<item_>();
    r2__x = r2->x.value();
    r2__x=-r2__x;
    return r2__x;
    
}

Dial::item_::item_(Dial *parentScope_)

    : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Item  >(this)
    , parentScope(parentScope_)
    , _y_binding(item__1481434427_bindingFunctor())
    , _height_binding(item__1797471572_bindingFunctor())
    , _x_binding(item__3592665794_bindingFunctor())
    , _width_binding(item__3770268640_bindingFunctor())
    , _visible_binding(item__3347951558_bindingFunctor())
    , image_height_binding(item__781781174_bindingFunctor())
    , image_width_binding(item__2959489308_bindingFunctor())
    , image_y_binding(item__3059855150_bindingFunctor())
    , image_x_binding(item__2022471783_bindingFunctor())
{
    _y_binding.init<item_, &item_::_y_binding>(y);
    // y: {
    // line 102  "Dial.qml"
    y.setBinding (&_y_binding);
    _height_binding.init<item_, &item_::_height_binding>(height);
    // height: {
    // line 89  "Dial.qml"
    height.setBinding (&_height_binding);
    _x_binding.init<item_, &item_::_x_binding>(x);
    // x: {
    // line 80  "Dial.qml"
    x.setBinding (&_x_binding);
    _width_binding.init<item_, &item_::_width_binding>(width);
    // width: {
    // line 67  "Dial.qml"
    width.setBinding (&_width_binding);
    _visible_binding.init<item_, &item_::_visible_binding>(visible);
    // visible: control.enabled
    // line 66  "Dial.qml"
    visible.setBinding (&_visible_binding);
    // clip: true;
    // line 65  "Dial.qml"
    itemExtraProperties->clip.setValue(true);
    // Image {
    // line 111  "Dial.qml"
    appendChild(this, &image);
    image_height_binding.init<item_, &item_::image_height_binding>(image.height);
    // height: backgroundImg.height
    // line 116  "Dial.qml"
    image.height.setBinding (&image_height_binding);
    image_width_binding.init<item_, &item_::image_width_binding>(image.width);
    // width: backgroundImg.width
    // line 115  "Dial.qml"
    image.width.setBinding (&image_width_binding);
    image_y_binding.init<item_, &item_::image_y_binding>(image.y);
    // y: -parent.y
    // line 114  "Dial.qml"
    image.y.setBinding (&image_y_binding);
    image_x_binding.init<item_, &item_::image_x_binding>(image.x);
    // x: -parent.x
    // line 113  "Dial.qml"
    image.x.setBinding (&image_x_binding);
    // source: "qrc:/images/dial-progress.png"
    // line 112  "Dial.qml"
    image.source.setValue(Qul::Private::ImagePrivate::fromRasterBuffer(qul_rasterBuffer_dial_2Dprogress_14694211536943410449_handle));
}

Qul::SharedImage Dial::Dial_494471238_bindingFunctor::operator()(Dial *self) const
{
    (void) self;
    bool r2__enabled;
    QUL_DECL_UNUSED Qul::Private::String r2_1;
    QUL_DECL_UNUSED Dial * r2 = NULL;
    // source: !control.enabled ? "qrc:/images/dial-background-disabled.png" : "qrc:/images/dial-background.png"
    // line 59  "Dial.qml"
    r2 = self;
    r2__enabled = r2->enabled.value();
    r2__enabled = !r2__enabled;
    if (!r2__enabled) goto label_0;;
    r2_1 = Qul::Private::String(Qul::Private::ImageIdValue::create("qrc:/images/dial-background-disabled.png", qul_rasterBuffer_dial_2Dbackground_2Ddisabled_15345896986866248576_handle), 40);
    goto label_1;;
    label_0:;
    r2_1 = Qul::Private::String(Qul::Private::ImageIdValue::create("qrc:/images/dial-background.png", qul_rasterBuffer_dial_2Dbackground_3190004907980333205_handle), 31);
    label_1:;
    return Qul::Private::findImageForString(r2_1);
    
}
int Dial::Dial_3959414088_bindingFunctor::operator()(Dial *self) const
{
    (void) self;
    int r8;
    int r2_2;
    Qul::qreal r2_1;
    QUL_DECL_UNUSED Dial * r2 = NULL;
    int r7__height;
    // y: (parent.height - height) / 2
    // line 58  "Dial.qml"
    r2 = self->backgroundImg.parent<Dial >();
    r2_2 = r2->height.value();
    r7__height = r2_2;
    r2_2 = self->backgroundImg.height.value();
    r2_2 = r7__height - r2_2;
    r8 = r2_2;
    r2_2 = 2;
    r2_1 = Qul::qreal(r8) / r2_2;
    return int(r2_1);
    
}
int Dial::Dial_258371655_bindingFunctor::operator()(Dial *self) const
{
    (void) self;
    int r8;
    int r2_2;
    Qul::qreal r2_1;
    QUL_DECL_UNUSED Dial * r2 = NULL;
    int r7__width;
    // x: (parent.width - width) / 2
    // line 57  "Dial.qml"
    r2 = self->backgroundImg.parent<Dial >();
    r2_2 = r2->width.value();
    r7__width = r2_2;
    r2_2 = self->backgroundImg.width.value();
    r2_2 = r7__width - r2_2;
    r8 = r2_2;
    r2_2 = 2;
    r2_1 = Qul::qreal(r8) / r2_2;
    return int(r2_1);
    
}
Qul::qreal Dial::Dial_2827309608_bindingFunctor::operator()(Dial *self) const
{
    (void) self;
    Qul::qreal r8;
    int r2_3;
    Qul::qreal r2_1;
    QUL_DECL_UNUSED Dial * r2 = NULL;
    QUL_DECL_UNUSED Qul::Private::Builtins::Math * r2_2 = NULL;
    Qul::qreal r9__PI;
    Qul::qreal r7__angle;
    // readonly property real angleRadians: (control.angle - 90) * (Math.PI / 180)
    // line 52  "Dial.qml"
    r2 = self;
    r2_1 = r2->angle.value();
    r7__angle = r2_1;
    r2_3 = 90;
    r2_1 = r7__angle - r2_3;
    r8 = r2_1;
    r2_2 = &Qul::Private::Builtins::Math ::instance();
    r2_1 = r2_2->PI.value();
    r9__PI = r2_1;
    r2_3 = 180;
    r2_1 = Qul::qreal(r9__PI) / r2_3;
    r2_1 = r8 * r2_1;
    return r2_1;
    
}
int Dial::Dial_738841179_bindingFunctor::operator()(Dial *self) const
{
    (void) self;
    Qul::qreal r9;
    int r2__height;
    Qul::qreal r2_1;
    QUL_DECL_UNUSED Dial * r2 = NULL;
    QUL_DECL_UNUSED Qul::Private::Builtins::Math * r2_3 = NULL;
    Qul::qreal r8;
    int r10;
    Qul::qreal r14;
    QUL_DECL_UNUSED Qul::Private::Builtins::Math * r11 = NULL;
    int r7__height;
    // y: (control.height / 2) - 15 + (95 * Math.sin(angleRadians))
    // line 50  "Dial.qml"
    r2 = self;
    r2__height = r2->height.value();
    r7__height = r2__height;
    r2__height = 2;
    r2_1 = Qul::qreal(r7__height) / r2__height;
    r8 = r2_1;
    r2__height = 15;
    r2_1 = r8 - r2__height;
    r9 = r2_1;
    r10 = 95;
    r2_3 = &Qul::Private::Builtins::Math ::instance();
    r11 = r2_3;
    r2_1 = self->handleImg.angleRadians.value();
    r14 = r2_1;
    r2_1 = r11->sin(r14);
    r2_1 = r10 * r2_1;
    r2_1 = r9 + r2_1;
    return int(r2_1);
    
}
int Dial::Dial_3392185257_bindingFunctor::operator()(Dial *self) const
{
    (void) self;
    Qul::qreal r9;
    int r2__width;
    Qul::qreal r2_1;
    QUL_DECL_UNUSED Dial * r2 = NULL;
    QUL_DECL_UNUSED Qul::Private::Builtins::Math * r2_3 = NULL;
    Qul::qreal r8;
    int r10;
    Qul::qreal r14;
    QUL_DECL_UNUSED Qul::Private::Builtins::Math * r11 = NULL;
    int r7__width;
    // x: (control.width / 2) - 21 + (95 * Math.cos(angleRadians))
    // line 49  "Dial.qml"
    r2 = self;
    r2__width = r2->width.value();
    r7__width = r2__width;
    r2__width = 2;
    r2_1 = Qul::qreal(r7__width) / r2__width;
    r8 = r2_1;
    r2__width = 21;
    r2_1 = r8 - r2__width;
    r9 = r2_1;
    r10 = 95;
    r2_3 = &Qul::Private::Builtins::Math ::instance();
    r11 = r2_3;
    r2_1 = self->handleImg.angleRadians.value();
    r14 = r2_1;
    r2_1 = r11->cos(r14);
    r2_1 = r10 * r2_1;
    r2_1 = r9 + r2_1;
    return int(r2_1);
    
}
int Dial::Dial_638361119_bindingFunctor::operator()(Dial *self) const
{
    (void) self;
    int r2_2;
    Qul::qreal r2_1;
    QUL_DECL_UNUSED Qul::Private::Builtins::Math * r2 = NULL;
    QUL_DECL_UNUSED Qul::Private::Items::ItemBase * r2_3 = NULL;
    int r10;
    int r12;
    int r11;
    QUL_DECL_UNUSED Qul::Private::Builtins::Math * r7 = NULL;
    int r13;
    // implicitHeight: Math.max((background ? background.implicitHeight : 0) + topInset + bottomInset,
    // line 30  "Dial.qml"
    r2 = &Qul::Private::Builtins::Math ::instance();
    r7 = r2;
    r2_3 = self->background.value();
    if (!r2_3) goto label_0;;
    r2_3 = self->background.value();
    r2_2 = r2_3->itemExtraProperties->implicitHeight.value();
    goto label_1;;
    label_0:;
    r2_2 = 0;
    label_1:;
    r12 = r2_2;
    r2_2 = self->topInset.value();
    r2_2 = r12 + r2_2;
    r13 = r2_2;
    r2_2 = self->bottomInset.value();
    r2_2 = r13 + r2_2;
    r10 = r2_2;
    // (contentItem ? contentItem.implicitHeight : 0) + topPadding + bottomPadding)
    // line 31  "Dial.qml"
    r2_3 = self->contentItem.value();
    if (!r2_3) goto label_2;;
    r2_3 = self->contentItem.value();
    r2_2 = r2_3->itemExtraProperties->implicitHeight.value();
    goto label_3;;
    label_2:;
    r2_2 = 0;
    label_3:;
    r12 = r2_2;
    r2_2 = self->topPadding.value();
    r2_2 = r12 + r2_2;
    r13 = r2_2;
    r2_2 = self->bottomPadding.value();
    r2_2 = r13 + r2_2;
    r11 = r2_2;
    r2_1 = r7->max(r10, r11);
    return int(r2_1);
    
}
int Dial::Dial_2791446706_bindingFunctor::operator()(Dial *self) const
{
    (void) self;
    int r2_2;
    Qul::qreal r2_1;
    QUL_DECL_UNUSED Qul::Private::Builtins::Math * r2 = NULL;
    QUL_DECL_UNUSED Qul::Private::Items::ItemBase * r2_3 = NULL;
    int r10;
    int r12;
    int r11;
    QUL_DECL_UNUSED Qul::Private::Builtins::Math * r7 = NULL;
    int r13;
    // implicitWidth: Math.max((background ? background.implicitWidth : 0) + leftInset + rightInset,
    // line 28  "Dial.qml"
    r2 = &Qul::Private::Builtins::Math ::instance();
    r7 = r2;
    r2_3 = self->background.value();
    if (!r2_3) goto label_0;;
    r2_3 = self->background.value();
    r2_2 = r2_3->itemExtraProperties->implicitWidth.value();
    goto label_1;;
    label_0:;
    r2_2 = 0;
    label_1:;
    r12 = r2_2;
    r2_2 = self->leftInset.value();
    r2_2 = r12 + r2_2;
    r13 = r2_2;
    r2_2 = self->rightInset.value();
    r2_2 = r13 + r2_2;
    r10 = r2_2;
    // (contentItem ? contentItem.implicitWidth : 0) + leftPadding + rightPadding)
    // line 29  "Dial.qml"
    r2_3 = self->contentItem.value();
    if (!r2_3) goto label_2;;
    r2_3 = self->contentItem.value();
    r2_2 = r2_3->itemExtraProperties->implicitWidth.value();
    goto label_3;;
    label_2:;
    r2_2 = 0;
    label_3:;
    r12 = r2_2;
    r2_2 = self->leftPadding.value();
    r2_2 = r12 + r2_2;
    r13 = r2_2;
    r2_2 = self->rightPadding.value();
    r2_2 = r13 + r2_2;
    r11 = r2_2;
    r2_1 = r7->max(r10, r11);
    return int(r2_1);
    
}

Dial::Dial()

    : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Controls::Templates::Dial  >(this)
    , repeater(this)
    , backgroundImg_source_binding(Dial_494471238_bindingFunctor())
    , backgroundImg_y_binding(Dial_3959414088_bindingFunctor())
    , backgroundImg_x_binding(Dial_258371655_bindingFunctor())
    , handleImg_angleRadians_binding(Dial_2827309608_bindingFunctor())
    , handleImg_y_binding(Dial_738841179_bindingFunctor())
    , handleImg_x_binding(Dial_3392185257_bindingFunctor())
    , _implicitHeight_binding(Dial_638361119_bindingFunctor())
    , _implicitWidth_binding(Dial_2791446706_bindingFunctor())
{
    backgroundImg_source_binding.init<Dial, &Dial::backgroundImg_source_binding>(backgroundImg.source);
    // source: !control.enabled ? "qrc:/images/dial-background-disabled.png" : "qrc:/images/dial-background.png"
    // line 59  "Dial.qml"
    backgroundImg.source.setBinding (&backgroundImg_source_binding);
    backgroundImg_y_binding.init<Dial, &Dial::backgroundImg_y_binding>(backgroundImg.y);
    // y: (parent.height - height) / 2
    // line 58  "Dial.qml"
    backgroundImg.y.setBinding (&backgroundImg_y_binding);
    backgroundImg_x_binding.init<Dial, &Dial::backgroundImg_x_binding>(backgroundImg.x);
    // x: (parent.width - width) / 2
    // line 57  "Dial.qml"
    backgroundImg.x.setBinding (&backgroundImg_x_binding);
    // Repeater {
    // line 61  "Dial.qml"
    appendChild(&this->backgroundImg, &repeater);
    // model: 4 // One for each quadrant
    // line 62  "Dial.qml"
    repeater.model.setValue(&repeater_model);
    // background: Image {
    // line 55  "Dial.qml"
    background.setValue(&backgroundImg);
    handleImg_angleRadians_binding.init<Dial, &Dial::handleImg_angleRadians_binding>(handleImg.angleRadians);
    // readonly property real angleRadians: (control.angle - 90) * (Math.PI / 180)
    // line 52  "Dial.qml"
    handleImg.angleRadians.setBinding (&handleImg_angleRadians_binding);
    // source: "qrc:/images/slider-handle.png"
    // line 51  "Dial.qml"
    handleImg.source.setValue(Qul::Private::ImagePrivate::fromRasterBuffer(qul_rasterBuffer_slider_2Dhandle_4014514759752923839_handle));
    handleImg_y_binding.init<Dial, &Dial::handleImg_y_binding>(handleImg.y);
    // y: (control.height / 2) - 15 + (95 * Math.sin(angleRadians))
    // line 50  "Dial.qml"
    handleImg.y.setBinding (&handleImg_y_binding);
    handleImg_x_binding.init<Dial, &Dial::handleImg_x_binding>(handleImg.x);
    // x: (control.width / 2) - 21 + (95 * Math.cos(angleRadians))
    // line 49  "Dial.qml"
    handleImg.x.setBinding (&handleImg_x_binding);
    // handle: Image {
    // line 43  "Dial.qml"
    handle.setValue(&handleImg);
    // bottomInset: DefaultStyle.inset
    // line 41  "Dial.qml"
    bottomInset.setValue(5);
    // rightInset: DefaultStyle.inset
    // line 40  "Dial.qml"
    rightInset.setValue(5);
    // topInset: DefaultStyle.inset
    // line 39  "Dial.qml"
    topInset.setValue(5);
    // leftInset: DefaultStyle.inset
    // line 38  "Dial.qml"
    leftInset.setValue(5);
    // bottomPadding: DefaultStyle.padding
    // line 36  "Dial.qml"
    bottomPadding.setValue(5);
    // topPadding: DefaultStyle.padding
    // line 35  "Dial.qml"
    topPadding.setValue(5);
    // rightPadding: DefaultStyle.padding
    // line 34  "Dial.qml"
    rightPadding.setValue(5);
    // leftPadding: DefaultStyle.padding
    // line 33  "Dial.qml"
    leftPadding.setValue(5);
    _implicitHeight_binding.init<Dial, &Dial::_implicitHeight_binding>(itemExtraProperties->implicitHeight);
    // implicitHeight: Math.max((background ? background.implicitHeight : 0) + topInset + bottomInset,
    // line 30  "Dial.qml"
    itemExtraProperties->implicitHeight.setBinding (&_implicitHeight_binding);
    _implicitWidth_binding.init<Dial, &Dial::_implicitWidth_binding>(itemExtraProperties->implicitWidth);
    // implicitWidth: Math.max((background ? background.implicitWidth : 0) + leftInset + rightInset,
    // line 28  "Dial.qml"
    itemExtraProperties->implicitWidth.setBinding (&_implicitWidth_binding);
}

} // namespace QtQuick
} // namespace Controls
} // namespace StyleDefault
