// This code is auto-generated by Qul's qmltocpp tool from the file 'Dial.qml'
// WARNING! All changes made in this file will be lost!
// NOTE: This generated API is to be considered implementation detail for Qul.
//       It may change from version to version and should not be relied upon.
#pragma once
#include "DefaultStyle.h"
#include <platforminterface/log.h>
#include <qul/image.h>
#include <qul/private/builtins.h>
#include <qul/private/controls/dialtemplate.h>
#include <qul/private/file.h>
#include <qul/private/items.h>
#include <qul/private/items/item.h>
#include <qul/private/models.h>
#include <qul/private/qulrcc_lookup.h>
#include <qul/private/unicodestring.h>
#include <qul/signal.h>

namespace QtQuick {
namespace Controls {
namespace StyleDefault {

struct Dial : Qul::Private::Controls::Templates::Dial , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Controls::Templates::Dial  > {
    Dial();


    Qul::Property<Qul::Private::String> state;
    struct item_ : Qul::Private::Items::Item , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Item  > {
        explicit item_(Dial *parentScope_);
        Dial * parentScope;


        Qul::Property<int> attached_index;
        typedef Qul::Private::Items::Image  image_Image;
        image_Image image;
        struct item__1481434427_bindingFunctor {
            int operator()(item_ *self) const;
        };
        Qul::Private::Binding<item__1481434427_bindingFunctor, 0> _y_binding;
        struct item__1797471572_bindingFunctor {
            int operator()(item_ *self) const;
        };
        Qul::Private::Binding<item__1797471572_bindingFunctor, 0> _height_binding;
        struct item__3592665794_bindingFunctor {
            int operator()(item_ *self) const;
        };
        Qul::Private::Binding<item__3592665794_bindingFunctor, 0> _x_binding;
        struct item__3770268640_bindingFunctor {
            int operator()(item_ *self) const;
        };
        Qul::Private::Binding<item__3770268640_bindingFunctor, 0> _width_binding;
        struct item__3347951558_bindingFunctor {
            bool operator()(item_ *self) const;
        };
        Qul::Private::Binding<item__3347951558_bindingFunctor, 0> _visible_binding;
        struct item__781781174_bindingFunctor {
            int operator()(item_ *self) const;
        };
        Qul::Private::Binding<item__781781174_bindingFunctor, 0> image_height_binding;
        struct item__2959489308_bindingFunctor {
            int operator()(item_ *self) const;
        };
        Qul::Private::Binding<item__2959489308_bindingFunctor, 0> image_width_binding;
        struct item__3059855150_bindingFunctor {
            int operator()(item_ *self) const;
        };
        Qul::Private::Binding<item__3059855150_bindingFunctor, 0> image_y_binding;
        struct item__2022471783_bindingFunctor {
            int operator()(item_ *self) const;
        };
        Qul::Private::Binding<item__2022471783_bindingFunctor, 0> image_x_binding;
    };
    Qul::Private::ConstIntegerModel<4> repeater_model;
    struct repeater_Repeater : Qul::Private::Items::Repeater <Qul::Private::ConstIntegerModel<4>, item_, Dial> {
        template<typename T> repeater_Repeater(const T &arg) : Qul::Private::Items::Repeater <Qul::Private::ConstIntegerModel<4>, item_, Dial>(arg) 
        {}
    } repeater;
    struct backgroundImg_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        backgroundImg_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } backgroundImg;
    struct handleImg_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        handleImg_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
        Qul::Property<Qul::qreal> angleRadians;
    } handleImg;
    struct Dial_494471238_bindingFunctor {
        Qul::SharedImage operator()(Dial *self) const;
    };
    Qul::Private::Binding<Dial_494471238_bindingFunctor, 0> backgroundImg_source_binding;
    struct Dial_3959414088_bindingFunctor {
        int operator()(Dial *self) const;
    };
    Qul::Private::Binding<Dial_3959414088_bindingFunctor, 0> backgroundImg_y_binding;
    struct Dial_258371655_bindingFunctor {
        int operator()(Dial *self) const;
    };
    Qul::Private::Binding<Dial_258371655_bindingFunctor, 0> backgroundImg_x_binding;
    struct Dial_2827309608_bindingFunctor {
        Qul::qreal operator()(Dial *self) const;
    };
    Qul::Private::Binding<Dial_2827309608_bindingFunctor, 0> handleImg_angleRadians_binding;
    struct Dial_738841179_bindingFunctor {
        int operator()(Dial *self) const;
    };
    Qul::Private::Binding<Dial_738841179_bindingFunctor, 0> handleImg_y_binding;
    struct Dial_3392185257_bindingFunctor {
        int operator()(Dial *self) const;
    };
    Qul::Private::Binding<Dial_3392185257_bindingFunctor, 0> handleImg_x_binding;
    struct Dial_638361119_bindingFunctor {
        int operator()(Dial *self) const;
    };
    Qul::Private::Binding<Dial_638361119_bindingFunctor, 0> _implicitHeight_binding;
    struct Dial_2791446706_bindingFunctor {
        int operator()(Dial *self) const;
    };
    Qul::Private::Binding<Dial_2791446706_bindingFunctor, 0> _implicitWidth_binding;
};

} // namespace QtQuick
} // namespace Controls
} // namespace StyleDefault
