// This code is auto-generated by Qul's qmltocpp tool from the file 'ProgressBar.qml'
// WARNING! All changes made in this file will be lost!
// NOTE: This generated API is to be considered implementation detail for Qul.
//       It may change from version to version and should not be relied upon.
#pragma once
#include "DefaultStyle.h"
#include <platforminterface/log.h>
#include <qul/image.h>
#include <qul/private/builtins.h>
#include <qul/private/controls/progressbartemplate.h>
#include <qul/private/file.h>
#include <qul/private/items.h>
#include <qul/private/items/item.h>
#include <qul/private/qulrcc_lookup.h>
#include <qul/private/unicodestring.h>
#include <qul/signal.h>

namespace QtQuick {
namespace Controls {
namespace StyleDefault {

struct ProgressBar : Qul::Private::Controls::Templates::ProgressBar , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Controls::Templates::ProgressBar  > {
    ProgressBar();


    Qul::Property<Qul::Private::String> state;
    typedef Qul::Private::Items::BorderImage  borderimage_2_BorderImage;
    borderimage_2_BorderImage borderimage_2;
    struct item__2_Item : Qul::Private::Items::Item , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Item  > {
        item__2_Item()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Item  >(this)
        {}
    } item__2;
    typedef Qul::Private::Items::BorderImage  borderimage_BorderImage;
    borderimage_BorderImage borderimage;
    struct item__Item : Qul::Private::Items::Item , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Item  > {
        item__Item()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Item  >(this)
        {}
    } item_;
    struct borderimage_2_y_anchor_bindingFunctor {
    int operator()(ProgressBar *self) const;
};
    Qul::Private::Binding<borderimage_2_y_anchor_bindingFunctor, 2> borderimage_2_y_anchor_binding;
    struct ProgressBar_1416228309_bindingFunctor {
        int operator()(ProgressBar *self) const;
    };
    Qul::Private::Binding<ProgressBar_1416228309_bindingFunctor, 0> borderimage_2_width_binding;
    struct borderimage_y_anchor_bindingFunctor {
    int operator()(ProgressBar *self) const;
};
    Qul::Private::Binding<borderimage_y_anchor_bindingFunctor, 2> borderimage_y_anchor_binding;
    struct ProgressBar_2580924395_bindingFunctor {
        int operator()(ProgressBar *self) const;
    };
    Qul::Private::Binding<ProgressBar_2580924395_bindingFunctor, 0> borderimage_width_binding;
    struct ProgressBar_638361119_bindingFunctor {
        int operator()(ProgressBar *self) const;
    };
    Qul::Private::Binding<ProgressBar_638361119_bindingFunctor, 0> _implicitHeight_binding;
    struct ProgressBar_2791446706_bindingFunctor {
        int operator()(ProgressBar *self) const;
    };
    Qul::Private::Binding<ProgressBar_2791446706_bindingFunctor, 0> _implicitWidth_binding;
};

} // namespace QtQuick
} // namespace Controls
} // namespace StyleDefault
