// This code is auto-generated by Qul's qmltocpp tool from the file 'ProgressBar.qml'
// WARNING! All changes made in this file will be lost!
#include "ProgressBar.h"
#include <qul/private/graphicsdevice.h>
#include <qul/private/filecache.h>

extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_progressbar_2Dprogress_13794051059923927174_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_progressbar_2Dbackground_14365083936487772959_handle;
static const Qul::Private::String qulCurrentFileDir(".", 1);
namespace QtQuick {
namespace Controls {
namespace StyleDefault {
extern Qul::Private::Items::ItemBase *loaderItemAllocator(const Qul::Private::String &uri, const Qul::Private::String &currentFileDir);

} // namespace QtQuick
} // namespace Controls
} // namespace StyleDefault
namespace Qul { namespace Private {
Qul::Property<int> &translationIndexProperty_da39a3ee5e6b4b0d3255bfef95601890afd80709();
extern const uint32_t *qul_translation_offsets_02fcf5ffd78f6a109eea4c4e4ac1496d65aac326();
extern const uint8_t *qul_translations_02fcf5ffd78f6a109eea4c4e4ac1496d65aac326();
}}

namespace QtQuick {
namespace Controls {
namespace StyleDefault {

namespace {
#if defined(QUL_CC_IAR)
#pragma diag_suppress=Pe177 // declared but never referenced
#elif defined(QUL_CC_GNU)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-function"
#endif
static Qul::Property<int> &translationIndexProperty() { return Qul::Private::translationIndexProperty_da39a3ee5e6b4b0d3255bfef95601890afd80709(); }
static int translationIndex() { return translationIndexProperty().value(); }
static const char *qul_translation(int entry) {
    const size_t translationLanguageCount = 1;
    const uint32_t *offsets = Qul::Private::qul_translation_offsets_02fcf5ffd78f6a109eea4c4e4ac1496d65aac326();
    const uint8_t *translations = Qul::Private::qul_translations_02fcf5ffd78f6a109eea4c4e4ac1496d65aac326();
    return reinterpret_cast<const char *>(&translations[offsets[entry * translationLanguageCount + translationIndex()]]);
}
#if defined(QUL_CC_IAR)
#pragma diag_default=Pe177 // declared but never referenced
#elif defined(QUL_CC_GNU)
#pragma GCC diagnostic pop
#endif
}


int ProgressBar::borderimage_2_y_anchor_bindingFunctor::operator()(ProgressBar *self) const {
        return int((int(self->item__2.height.value()) + 1)/2 - ((self->borderimage_2.height.value())/2.0));
}
int ProgressBar::ProgressBar_1416228309_bindingFunctor::operator()(ProgressBar *self) const
{
    (void) self;
    int r2__width;
    QUL_DECL_UNUSED ProgressBar * r2_3 = NULL;
    Qul::qreal r2__position;
    QUL_DECL_UNUSED item__2_Item * r2 = NULL;
    int r7__width;
    // width: parent.width * root.position; height: 16
    // line 58  "ProgressBar.qml"
    r2 = self->borderimage_2.parent<item__2_Item >();
    r2__width = r2->width.value();
    r7__width = r2__width;
    r2_3 = self;
    r2__position = r2_3->position.value();
    r2__position = r7__width * r2__position;
    return int(r2__position);
    
}
int ProgressBar::borderimage_y_anchor_bindingFunctor::operator()(ProgressBar *self) const {
        return int((int(self->item_.height.value()) + 1)/2 - ((self->borderimage.height.value())/2.0));
}
int ProgressBar::ProgressBar_2580924395_bindingFunctor::operator()(ProgressBar *self) const
{
    (void) self;
    QUL_DECL_UNUSED item__Item * r2 = NULL;
    int r2__width;
    // width: parent.width; height: 16
    // line 45  "ProgressBar.qml"
    r2 = self->borderimage.parent<item__Item >();
    r2__width = r2->width.value();
    return r2__width;
    
}
int ProgressBar::ProgressBar_638361119_bindingFunctor::operator()(ProgressBar *self) const
{
    (void) self;
    int r2_2;
    Qul::qreal r2_1;
    QUL_DECL_UNUSED Qul::Private::Builtins::Math * r2 = NULL;
    QUL_DECL_UNUSED Qul::Private::Items::ItemBase * r2_3 = NULL;
    int r10;
    int r12;
    int r11;
    QUL_DECL_UNUSED Qul::Private::Builtins::Math * r7 = NULL;
    int r13;
    // implicitHeight: Math.max((background ? background.implicitHeight : 0) + topInset + bottomInset,
    // line 30  "ProgressBar.qml"
    r2 = &Qul::Private::Builtins::Math ::instance();
    r7 = r2;
    r2_3 = self->background.value();
    if (!r2_3) goto label_0;;
    r2_3 = self->background.value();
    r2_2 = r2_3->itemExtraProperties->implicitHeight.value();
    goto label_1;;
    label_0:;
    r2_2 = 0;
    label_1:;
    r12 = r2_2;
    r2_2 = self->topInset.value();
    r2_2 = r12 + r2_2;
    r13 = r2_2;
    r2_2 = self->bottomInset.value();
    r2_2 = r13 + r2_2;
    r10 = r2_2;
    // (contentItem ? contentItem.implicitHeight : 0) + topPadding + bottomPadding)
    // line 31  "ProgressBar.qml"
    r2_3 = self->contentItem.value();
    if (!r2_3) goto label_2;;
    r2_3 = self->contentItem.value();
    r2_2 = r2_3->itemExtraProperties->implicitHeight.value();
    goto label_3;;
    label_2:;
    r2_2 = 0;
    label_3:;
    r12 = r2_2;
    r2_2 = self->topPadding.value();
    r2_2 = r12 + r2_2;
    r13 = r2_2;
    r2_2 = self->bottomPadding.value();
    r2_2 = r13 + r2_2;
    r11 = r2_2;
    r2_1 = r7->max(r10, r11);
    return int(r2_1);
    
}
int ProgressBar::ProgressBar_2791446706_bindingFunctor::operator()(ProgressBar *self) const
{
    (void) self;
    int r2_2;
    Qul::qreal r2_1;
    QUL_DECL_UNUSED Qul::Private::Builtins::Math * r2 = NULL;
    QUL_DECL_UNUSED Qul::Private::Items::ItemBase * r2_3 = NULL;
    int r10;
    int r12;
    int r11;
    QUL_DECL_UNUSED Qul::Private::Builtins::Math * r7 = NULL;
    int r13;
    // implicitWidth: Math.max((background ? background.implicitWidth : 0) + leftInset + rightInset,
    // line 28  "ProgressBar.qml"
    r2 = &Qul::Private::Builtins::Math ::instance();
    r7 = r2;
    r2_3 = self->background.value();
    if (!r2_3) goto label_0;;
    r2_3 = self->background.value();
    r2_2 = r2_3->itemExtraProperties->implicitWidth.value();
    goto label_1;;
    label_0:;
    r2_2 = 0;
    label_1:;
    r12 = r2_2;
    r2_2 = self->leftInset.value();
    r2_2 = r12 + r2_2;
    r13 = r2_2;
    r2_2 = self->rightInset.value();
    r2_2 = r13 + r2_2;
    r10 = r2_2;
    // (contentItem ? contentItem.implicitWidth : 0) + leftPadding + rightPadding)
    // line 29  "ProgressBar.qml"
    r2_3 = self->contentItem.value();
    if (!r2_3) goto label_2;;
    r2_3 = self->contentItem.value();
    r2_2 = r2_3->itemExtraProperties->implicitWidth.value();
    goto label_3;;
    label_2:;
    r2_2 = 0;
    label_3:;
    r12 = r2_2;
    r2_2 = self->leftPadding.value();
    r2_2 = r12 + r2_2;
    r13 = r2_2;
    r2_2 = self->rightPadding.value();
    r2_2 = r13 + r2_2;
    r11 = r2_2;
    r2_1 = r7->max(r10, r11);
    return int(r2_1);
    
}

ProgressBar::ProgressBar()

    : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Controls::Templates::ProgressBar  >(this)
    , borderimage_2_y_anchor_binding(borderimage_2_y_anchor_bindingFunctor())
    , borderimage_2_width_binding(ProgressBar_1416228309_bindingFunctor())
    , borderimage_y_anchor_binding(borderimage_y_anchor_bindingFunctor())
    , borderimage_width_binding(ProgressBar_2580924395_bindingFunctor())
    , _implicitHeight_binding(ProgressBar_638361119_bindingFunctor())
    , _implicitWidth_binding(ProgressBar_2791446706_bindingFunctor())
{
    // implicitHeight: 16
    // line 56  "ProgressBar.qml"
    item__2.itemExtraProperties->implicitHeight.setValue(16);
    // implicitWidth: 200
    // line 55  "ProgressBar.qml"
    item__2.itemExtraProperties->implicitWidth.setValue(200);
    // BorderImage {
    // line 57  "ProgressBar.qml"
    appendChild(&this->item__2, &borderimage_2);
    // source: "qrc:/images/progressbar-progress.png"
    // line 64  "ProgressBar.qml"
    borderimage_2.source.setValue(Qul::Private::ImagePrivate::fromRasterBuffer(qul_rasterBuffer_progressbar_2Dprogress_13794051059923927174_handle));
    // border.bottom: 7
    // line 63  "ProgressBar.qml"
    borderimage_2.border.bottom.setValue(7);
    // border.top: 7
    // line 62  "ProgressBar.qml"
    borderimage_2.border.top.setValue(7);
    // border.right: 6
    // line 61  "ProgressBar.qml"
    borderimage_2.border.right.setValue(6);
    // border.left: 6
    // line 60  "ProgressBar.qml"
    borderimage_2.border.left.setValue(6);
    borderimage_2_y_anchor_binding.init<ProgressBar, &ProgressBar::borderimage_2_y_anchor_binding>(borderimage_2.y);
    borderimage_2.y.setBinding(&borderimage_2_y_anchor_binding);
    // width: parent.width * root.position; height: 16
    // line 58  "ProgressBar.qml"
    borderimage_2.height.setValue(16);
    borderimage_2_width_binding.init<ProgressBar, &ProgressBar::borderimage_2_width_binding>(borderimage_2.width);
    // width: parent.width * root.position; height: 16
    // line 58  "ProgressBar.qml"
    borderimage_2.width.setBinding (&borderimage_2_width_binding);
    // contentItem: Item {
    // line 54  "ProgressBar.qml"
    contentItem.setValue(&item__2);
    // implicitHeight: 16
    // line 43  "ProgressBar.qml"
    item_.itemExtraProperties->implicitHeight.setValue(16);
    // implicitWidth: 200
    // line 42  "ProgressBar.qml"
    item_.itemExtraProperties->implicitWidth.setValue(200);
    // BorderImage {
    // line 44  "ProgressBar.qml"
    appendChild(&this->item_, &borderimage);
    // source: "qrc:/images/progressbar-background.png"
    // line 51  "ProgressBar.qml"
    borderimage.source.setValue(Qul::Private::ImagePrivate::fromRasterBuffer(qul_rasterBuffer_progressbar_2Dbackground_14365083936487772959_handle));
    // border.bottom: 7
    // line 50  "ProgressBar.qml"
    borderimage.border.bottom.setValue(7);
    // border.top: 7
    // line 49  "ProgressBar.qml"
    borderimage.border.top.setValue(7);
    // border.right: 7
    // line 48  "ProgressBar.qml"
    borderimage.border.right.setValue(7);
    // border.left: 7
    // line 47  "ProgressBar.qml"
    borderimage.border.left.setValue(7);
    borderimage_y_anchor_binding.init<ProgressBar, &ProgressBar::borderimage_y_anchor_binding>(borderimage.y);
    borderimage.y.setBinding(&borderimage_y_anchor_binding);
    // width: parent.width; height: 16
    // line 45  "ProgressBar.qml"
    borderimage.height.setValue(16);
    borderimage_width_binding.init<ProgressBar, &ProgressBar::borderimage_width_binding>(borderimage.width);
    // width: parent.width; height: 16
    // line 45  "ProgressBar.qml"
    borderimage.width.setBinding (&borderimage_width_binding);
    // background: Item {
    // line 41  "ProgressBar.qml"
    background.setValue(&item_);
    // bottomPadding: DefaultStyle.padding
    // line 40  "ProgressBar.qml"
    bottomPadding.setValue(5);
    // rightPadding: DefaultStyle.padding
    // line 39  "ProgressBar.qml"
    rightPadding.setValue(5);
    // topPadding: DefaultStyle.padding
    // line 38  "ProgressBar.qml"
    topPadding.setValue(5);
    // leftPadding: DefaultStyle.padding
    // line 37  "ProgressBar.qml"
    leftPadding.setValue(5);
    // bottomInset: DefaultStyle.inset
    // line 36  "ProgressBar.qml"
    bottomInset.setValue(5);
    // rightInset: DefaultStyle.inset
    // line 35  "ProgressBar.qml"
    rightInset.setValue(5);
    // topInset: DefaultStyle.inset
    // line 34  "ProgressBar.qml"
    topInset.setValue(5);
    // leftInset: DefaultStyle.inset
    // line 33  "ProgressBar.qml"
    leftInset.setValue(5);
    _implicitHeight_binding.init<ProgressBar, &ProgressBar::_implicitHeight_binding>(itemExtraProperties->implicitHeight);
    // implicitHeight: Math.max((background ? background.implicitHeight : 0) + topInset + bottomInset,
    // line 30  "ProgressBar.qml"
    itemExtraProperties->implicitHeight.setBinding (&_implicitHeight_binding);
    _implicitWidth_binding.init<ProgressBar, &ProgressBar::_implicitWidth_binding>(itemExtraProperties->implicitWidth);
    // implicitWidth: Math.max((background ? background.implicitWidth : 0) + leftInset + rightInset,
    // line 28  "ProgressBar.qml"
    itemExtraProperties->implicitWidth.setBinding (&_implicitWidth_binding);
}

} // namespace QtQuick
} // namespace Controls
} // namespace StyleDefault
