// This code is auto-generated by Qul's qmltocpp tool from the file 'RadioButton.qml'
// WARNING! All changes made in this file will be lost!
#include "RadioButton.h"
#include <qul/private/graphicsdevice.h>
#include <qul/private/filecache.h>

extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_radiobutton_2Ddisabled_2924171873965041612_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_radiobutton_2Dchecked_2Dpressed_1045045686096008533_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_radiobutton_2Dchecked_5511976546139964538_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_radiobutton_2Dpressed_2579755744388265124_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_radiobutton_18216712924164089054_handle;
static const Qul::Private::String qulCurrentFileDir(".", 1);
namespace QtQuick {
namespace Controls {
namespace StyleDefault {
extern Qul::Private::Items::ItemBase *loaderItemAllocator(const Qul::Private::String &uri, const Qul::Private::String &currentFileDir);

} // namespace QtQuick
} // namespace Controls
} // namespace StyleDefault
namespace Qul { namespace Private {
Qul::Property<int> &translationIndexProperty_da39a3ee5e6b4b0d3255bfef95601890afd80709();
extern const uint32_t *qul_translation_offsets_d4c3e53ac8b0590d871d84e8a750fc2741ca221d();
extern const uint8_t *qul_translations_d4c3e53ac8b0590d871d84e8a750fc2741ca221d();
}}

namespace QtQuick {
namespace Controls {
namespace StyleDefault {

namespace {
#if defined(QUL_CC_IAR)
#pragma diag_suppress=Pe177 // declared but never referenced
#elif defined(QUL_CC_GNU)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-function"
#endif
static Qul::Property<int> &translationIndexProperty() { return Qul::Private::translationIndexProperty_da39a3ee5e6b4b0d3255bfef95601890afd80709(); }
static int translationIndex() { return translationIndexProperty().value(); }
static const char *qul_translation(int entry) {
    const size_t translationLanguageCount = 1;
    const uint32_t *offsets = Qul::Private::qul_translation_offsets_d4c3e53ac8b0590d871d84e8a750fc2741ca221d();
    const uint8_t *translations = Qul::Private::qul_translations_d4c3e53ac8b0590d871d84e8a750fc2741ca221d();
    return reinterpret_cast<const char *>(&translations[offsets[entry * translationLanguageCount + translationIndex()]]);
}
#if defined(QUL_CC_IAR)
#pragma diag_default=Pe177 // declared but never referenced
#elif defined(QUL_CC_GNU)
#pragma GCC diagnostic pop
#endif
}


int RadioButton::RadioButton_2567012512_bindingFunctor::operator()(RadioButton *self) const
{
    (void) self;
    int r2_1;
    QUL_DECL_UNUSED RadioButton * r2 = NULL;
    QUL_DECL_UNUSED Qul::Private::Items::ItemBase * r2__indicator = NULL;
    int r7__indicator_width;
    // implicitWidth: control.indicator ? control.indicator.width + control.spacing : 0
    // line 69  "RadioButton.qml"
    r2 = self;
    r2__indicator = r2->indicator.value();
    if (!r2__indicator) {
    goto label_0;};
    r2 = self;
    r2__indicator = r2->indicator.value();
    r2_1 = r2__indicator->width.value();
    r7__indicator_width = r2_1;
    r2 = self;
    r2_1 = r2->spacing.value();
    r2_1 = r7__indicator_width + r2_1;
    goto label_1;;
    {
    }
    label_0:;
    r2_1 = 0;
    label_1:;
    return r2_1;
    
}
int RadioButton::text__y_anchor_bindingFunctor::operator()(RadioButton *self) const {
        return int((int(self->row.height.value()) + 1)/2 - ((self->text_.height.value())/2.0));
}
Qul::PlatformInterface::Rgba32 RadioButton::RadioButton_641531737_bindingFunctor::operator()(RadioButton *self) const
{
    (void) self;
    QUL_DECL_UNUSED Qul::PlatformInterface::Rgba32 r2__disabledTextColor;
    bool r2__enabled;
    QUL_DECL_UNUSED RadioButton * r2 = NULL;
    QUL_DECL_UNUSED  ::QtQuick::Controls::StyleDefault::DefaultStyle * r2_3 = NULL;
    // color: control.enabled ? DefaultStyle.textColor : DefaultStyle.disabledTextColor
    // line 75  "RadioButton.qml"
    r2 = self;
    r2__enabled = r2->enabled.value();
    if (!r2__enabled) goto label_0;;
    r2_3 = & ::QtQuick::Controls::StyleDefault::DefaultStyle ::instance();
    r2__disabledTextColor = r2_3->textColor.value();
    goto label_1;;
    label_0:;
    r2_3 = & ::QtQuick::Controls::StyleDefault::DefaultStyle ::instance();
    r2__disabledTextColor = r2_3->disabledTextColor.value();
    label_1:;
    return r2__disabledTextColor;
    
}
Qul::Private::FontPointer RadioButton::RadioButton_350459312_bindingFunctor::operator()(RadioButton *self) const
{
    (void) self;
    QUL_DECL_UNUSED RadioButton * r2 = NULL;
    QUL_DECL_UNUSED Qul::Private::FontPointer r2__font;
    // font: control.font
    // line 74  "RadioButton.qml"
    r2 = self;
    r2__font = r2->font.value();
    return r2__font;
    
}
Qul::Private::String RadioButton::RadioButton_4011053975_bindingFunctor::operator()(RadioButton *self) const
{
    (void) self;
    QUL_DECL_UNUSED RadioButton * r2 = NULL;
    QUL_DECL_UNUSED Qul::Private::String r2__text;
    // text: control.text
    // line 73  "RadioButton.qml"
    r2 = self;
    r2__text = r2->text.value();
    return r2__text;
    
}
Qul::SharedImage RadioButton::RadioButton_1369550977_bindingFunctor::operator()(RadioButton *self) const
{
    (void) self;
    bool r2__down;
    QUL_DECL_UNUSED RadioButton * r2 = NULL;
    QUL_DECL_UNUSED Qul::Private::String r2_2;
    /*
    source: !control.enabled
    ? "qrc:/images/radiobutton-disabled.png"
    */
    // line 53  "RadioButton.qml"
    r2 = self;
    r2__down = r2->enabled.value();
    r2__down = !r2__down;
    if (!r2__down) goto label_0;;
    r2_2 = Qul::Private::String(Qul::Private::ImageIdValue::create("qrc:/images/radiobutton-disabled.png", qul_rasterBuffer_radiobutton_2Ddisabled_2924171873965041612_handle), 36);
    goto label_1;;
    label_0:;
    r2 = self;
    // : (control.checked
    // line 55  "RadioButton.qml"
    r2__down = r2->checked.value();
    if (!r2__down) goto label_2;;
    r2 = self;
    // ? (control.down ? "qrc:/images/radiobutton-checked-pressed.png" : "qrc:/images/radiobutton-checked.png")
    // line 56  "RadioButton.qml"
    r2__down = r2->down.value();
    if (!r2__down) goto label_3;;
    r2_2 = Qul::Private::String(Qul::Private::ImageIdValue::create("qrc:/images/radiobutton-checked-pressed.png", qul_rasterBuffer_radiobutton_2Dchecked_2Dpressed_1045045686096008533_handle), 43);
    goto label_4;;
    label_3:;
    r2_2 = Qul::Private::String(Qul::Private::ImageIdValue::create("qrc:/images/radiobutton-checked.png", qul_rasterBuffer_radiobutton_2Dchecked_5511976546139964538_handle), 35);
    label_4:;
    goto label_1;;
    label_2:;
    r2 = self;
    // : (control.down ? "qrc:/images/radiobutton-pressed.png" : "qrc:/images/radiobutton.png"))
    // line 57  "RadioButton.qml"
    r2__down = r2->down.value();
    if (!r2__down) goto label_5;;
    r2_2 = Qul::Private::String(Qul::Private::ImageIdValue::create("qrc:/images/radiobutton-pressed.png", qul_rasterBuffer_radiobutton_2Dpressed_2579755744388265124_handle), 35);
    goto label_1;;
    label_5:;
    r2_2 = Qul::Private::String(Qul::Private::ImageIdValue::create("qrc:/images/radiobutton.png", qul_rasterBuffer_radiobutton_18216712924164089054_handle), 27);
    label_1:;
    return Qul::Private::findImageForString(r2_2);
    
}
int RadioButton::RadioButton_1494144167_bindingFunctor::operator()(RadioButton *self) const
{
    (void) self;
    int r8__availableHeight;
    int r2_2;
    QUL_DECL_UNUSED RadioButton * r2 = NULL;
    Qul::qreal r2_1;
    int r9;
    int r7__topPadding;
    // y: control.topPadding + (control.availableHeight - height) / 2
    // line 52  "RadioButton.qml"
    r2 = self;
    r2_2 = r2->topPadding.value();
    r7__topPadding = r2_2;
    r2 = self;
    r2_2 = r2->availableHeight.value();
    r8__availableHeight = r2_2;
    r2_2 = self->image.height.value();
    r2_2 = r8__availableHeight - r2_2;
    r9 = r2_2;
    r2_2 = 2;
    r2_1 = Qul::qreal(r9) / r2_2;
    r2_1 = r7__topPadding + r2_1;
    return int(r2_1);
    
}
int RadioButton::RadioButton_1550939256_bindingFunctor::operator()(RadioButton *self) const
{
    (void) self;
    int r2__leftPadding;
    QUL_DECL_UNUSED RadioButton * r2 = NULL;
    // x: control.leftPadding
    // line 51  "RadioButton.qml"
    r2 = self;
    r2__leftPadding = r2->leftPadding.value();
    return r2__leftPadding;
    
}
int RadioButton::RadioButton_3560203182_bindingFunctor::operator()(RadioButton *self) const
{
    (void) self;
    QUL_DECL_UNUSED Qul::Private::Builtins::Math * r7 = NULL;
    int r13;
    int r16;
    int r2_1;
    Qul::qreal r2_3;
    QUL_DECL_UNUSED Qul::Private::Builtins::Math * r2 = NULL;
    QUL_DECL_UNUSED Qul::Private::Items::ItemBase * r2_2 = NULL;
    int r10;
    int r12_1;
    QUL_DECL_UNUSED Qul::Private::Builtins::Math * r12 = NULL;
    int r17;
    int r15;
    Qul::qreal r11;
    int r18;
    // implicitHeight: Math.max((background ? background.implicitHeight : 0) + topInset + bottomInset,
    // line 34  "RadioButton.qml"
    r2 = &Qul::Private::Builtins::Math ::instance();
    r7 = r2;
    r2_2 = self->background.value();
    if (!r2_2) goto label_0;;
    r2_2 = self->background.value();
    r2_1 = r2_2->itemExtraProperties->implicitHeight.value();
    goto label_1;;
    label_0:;
    r2_1 = 0;
    label_1:;
    r12_1 = r2_1;
    r2_1 = self->topInset.value();
    r2_1 = r12_1 + r2_1;
    r13 = r2_1;
    r2_1 = self->bottomInset.value();
    r2_1 = r13 + r2_1;
    r10 = r2_1;
    r2 = &Qul::Private::Builtins::Math ::instance();
    r12 = r2;
    // Math.max((contentItem ? contentItem.implicitHeight : 0) + topPadding + bottomPadding,
    // line 35  "RadioButton.qml"
    r2_2 = self->contentItem.value();
    if (!r2_2) goto label_2;;
    r2_2 = self->contentItem.value();
    r2_1 = r2_2->itemExtraProperties->implicitHeight.value();
    goto label_3;;
    label_2:;
    r2_1 = 0;
    label_3:;
    r17 = r2_1;
    r2_1 = self->topPadding.value();
    r2_1 = r17 + r2_1;
    r18 = r2_1;
    r2_1 = self->bottomPadding.value();
    r2_1 = r18 + r2_1;
    r15 = r2_1;
    // (indicator ? indicator.implicitHeight : 0) + topPadding + bottomPadding))
    // line 36  "RadioButton.qml"
    r2_2 = self->indicator.value();
    if (!r2_2) goto label_4;;
    r2_2 = self->indicator.value();
    r2_1 = r2_2->itemExtraProperties->implicitHeight.value();
    goto label_5;;
    label_4:;
    r2_1 = 0;
    label_5:;
    r17 = r2_1;
    r2_1 = self->topPadding.value();
    r2_1 = r17 + r2_1;
    r18 = r2_1;
    r2_1 = self->bottomPadding.value();
    r2_1 = r18 + r2_1;
    r16 = r2_1;
    r2_3 = r12->max(r15, r16);
    r11 = r2_3;
    r2_3 = r7->max(r10, r11);
    return int(r2_3);
    
}
int RadioButton::RadioButton_2791446706_bindingFunctor::operator()(RadioButton *self) const
{
    (void) self;
    int r2_2;
    Qul::qreal r2_1;
    QUL_DECL_UNUSED Qul::Private::Builtins::Math * r2 = NULL;
    QUL_DECL_UNUSED Qul::Private::Items::ItemBase * r2_3 = NULL;
    int r10;
    int r12;
    int r11;
    QUL_DECL_UNUSED Qul::Private::Builtins::Math * r7 = NULL;
    int r13;
    // implicitWidth: Math.max((background ? background.implicitWidth : 0) + leftInset + rightInset,
    // line 28  "RadioButton.qml"
    r2 = &Qul::Private::Builtins::Math ::instance();
    r7 = r2;
    r2_3 = self->background.value();
    if (!r2_3) goto label_0;;
    r2_3 = self->background.value();
    r2_2 = r2_3->itemExtraProperties->implicitWidth.value();
    goto label_1;;
    label_0:;
    r2_2 = 0;
    label_1:;
    r12 = r2_2;
    r2_2 = self->leftInset.value();
    r2_2 = r12 + r2_2;
    r13 = r2_2;
    r2_2 = self->rightInset.value();
    r2_2 = r13 + r2_2;
    r10 = r2_2;
    // (contentItem ? contentItem.implicitWidth : 0) + leftPadding + rightPadding)
    // line 29  "RadioButton.qml"
    r2_3 = self->contentItem.value();
    if (!r2_3) goto label_2;;
    r2_3 = self->contentItem.value();
    r2_2 = r2_3->itemExtraProperties->implicitWidth.value();
    goto label_3;;
    label_2:;
    r2_2 = 0;
    label_3:;
    r12 = r2_2;
    r2_2 = self->leftPadding.value();
    r2_2 = r12 + r2_2;
    r13 = r2_2;
    r2_2 = self->rightPadding.value();
    r2_2 = r13 + r2_2;
    r11 = r2_2;
    r2_1 = r7->max(r10, r11);
    return int(r2_1);
    
}

RadioButton::RadioButton()

    : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Controls::Templates::RadioButton  >(this)
    , item__2_implicitWidth_binding(RadioButton_2567012512_bindingFunctor())
    , text__y_anchor_binding(text__y_anchor_bindingFunctor())
    , text__color_binding(RadioButton_641531737_bindingFunctor())
    , font_font_binding(RadioButton_350459312_bindingFunctor())
    , text__text_binding(RadioButton_4011053975_bindingFunctor())
    , image_source_binding(RadioButton_1369550977_bindingFunctor())
    , image_y_binding(RadioButton_1494144167_bindingFunctor())
    , image_x_binding(RadioButton_1550939256_bindingFunctor())
    , _implicitHeight_binding(RadioButton_3560203182_bindingFunctor())
    , _implicitWidth_binding(RadioButton_2791446706_bindingFunctor())
{
    // Item {
    // line 68  "RadioButton.qml"
    appendChild(&this->row, &item__2);
    item__2_implicitWidth_binding.init<RadioButton, &RadioButton::item__2_implicitWidth_binding>(item__2.itemExtraProperties->implicitWidth);
    // implicitWidth: control.indicator ? control.indicator.width + control.spacing : 0
    // line 69  "RadioButton.qml"
    item__2.itemExtraProperties->implicitWidth.setBinding (&item__2_implicitWidth_binding);
    // Text {
    // line 72  "RadioButton.qml"
    appendChild(&this->row, &text_);
    text__y_anchor_binding.init<RadioButton, &RadioButton::text__y_anchor_binding>(text_.y);
    text_.y.setBinding(&text__y_anchor_binding);
    text__color_binding.init<RadioButton, &RadioButton::text__color_binding>(text_.color);
    // color: control.enabled ? DefaultStyle.textColor : DefaultStyle.disabledTextColor
    // line 75  "RadioButton.qml"
    text_.color.setBinding (&text__color_binding);
    font_font_binding.init<RadioButton, &RadioButton::font_font_binding>(text_.font);
    // font: control.font
    // line 74  "RadioButton.qml"
    text_.font.setBinding (&font_font_binding);
    text__text_binding.init<RadioButton, &RadioButton::text__text_binding>(text_.text);
    // text: control.text
    // line 73  "RadioButton.qml"
    text_.text.setBinding (&text__text_binding);
    // contentItem: Row {
    // line 67  "RadioButton.qml"
    contentItem.setValue(&row);
    // implicitHeight: 42
    // line 63  "RadioButton.qml"
    item_.itemExtraProperties->implicitHeight.setValue(42);
    // implicitWidth: 100
    // line 62  "RadioButton.qml"
    item_.itemExtraProperties->implicitWidth.setValue(100);
    // background: Item {
    // line 61  "RadioButton.qml"
    background.setValue(&item_);
    image_source_binding.init<RadioButton, &RadioButton::image_source_binding>(image.source);
    // source: !control.enabled
    // line 53  "RadioButton.qml"
    image.source.setBinding (&image_source_binding);
    image_y_binding.init<RadioButton, &RadioButton::image_y_binding>(image.y);
    // y: control.topPadding + (control.availableHeight - height) / 2
    // line 52  "RadioButton.qml"
    image.y.setBinding (&image_y_binding);
    image_x_binding.init<RadioButton, &RadioButton::image_x_binding>(image.x);
    // x: control.leftPadding
    // line 51  "RadioButton.qml"
    image.x.setBinding (&image_x_binding);
    // indicator: Image {
    // line 50  "RadioButton.qml"
    indicator.setValue(&image);
    // spacing: 10
    // line 48  "RadioButton.qml"
    spacing.setValue(10);
    // bottomInset: DefaultStyle.inset
    // line 46  "RadioButton.qml"
    bottomInset.setValue(5);
    // rightInset: DefaultStyle.inset
    // line 45  "RadioButton.qml"
    rightInset.setValue(5);
    // topInset: DefaultStyle.inset
    // line 44  "RadioButton.qml"
    topInset.setValue(5);
    // leftInset: DefaultStyle.inset
    // line 43  "RadioButton.qml"
    leftInset.setValue(5);
    // bottomPadding: DefaultStyle.padding
    // line 41  "RadioButton.qml"
    bottomPadding.setValue(5);
    // topPadding: DefaultStyle.padding
    // line 40  "RadioButton.qml"
    topPadding.setValue(5);
    // rightPadding: DefaultStyle.padding
    // line 39  "RadioButton.qml"
    rightPadding.setValue(5);
    // leftPadding: DefaultStyle.padding
    // line 38  "RadioButton.qml"
    leftPadding.setValue(5);
    _implicitHeight_binding.init<RadioButton, &RadioButton::_implicitHeight_binding>(itemExtraProperties->implicitHeight);
    // implicitHeight: Math.max((background ? background.implicitHeight : 0) + topInset + bottomInset,
    // line 34  "RadioButton.qml"
    itemExtraProperties->implicitHeight.setBinding (&_implicitHeight_binding);
    _implicitWidth_binding.init<RadioButton, &RadioButton::_implicitWidth_binding>(itemExtraProperties->implicitWidth);
    // implicitWidth: Math.max((background ? background.implicitWidth : 0) + leftInset + rightInset,
    // line 28  "RadioButton.qml"
    itemExtraProperties->implicitWidth.setBinding (&_implicitWidth_binding);
}

} // namespace QtQuick
} // namespace Controls
} // namespace StyleDefault
