// This code is auto-generated by Qul's qmltocpp tool from the file 'RadioButton.qml'
// WARNING! All changes made in this file will be lost!
// NOTE: This generated API is to be considered implementation detail for Qul.
//       It may change from version to version and should not be relied upon.
#pragma once
#include "DefaultStyle.h"
#include <platforminterface/log.h>
#include <qul/image.h>
#include <qul/private/builtins.h>
#include <qul/private/controls/radiobuttontemplate.h>
#include <qul/private/file.h>
#include <qul/private/items.h>
#include <qul/private/items/item.h>
#include <qul/private/items/text.h>
#include <qul/private/qulrcc_lookup.h>
#include <qul/private/unicodestring.h>
#include <qul/signal.h>

namespace QtQuick {
namespace Controls {
namespace StyleDefault {

struct RadioButton : Qul::Private::Controls::Templates::RadioButton , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Controls::Templates::RadioButton  > {
    RadioButton();


    Qul::Property<Qul::Private::String> state;
    struct item__2_Item : Qul::Private::Items::Item , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Item  > {
        item__2_Item()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Item  >(this)
        {}
    } item__2;
    typedef Qul::Private::Items::TextLight  text__Text;
    text__Text text_;
    struct row_Row : Qul::Private::Items::Row , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Row  > {
        row_Row()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Row  >(this)
        {}
    } row;
    struct item__Item : Qul::Private::Items::Item , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Item  > {
        item__Item()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Item  >(this)
        {}
    } item_;
    struct image_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        image_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } image;
    struct RadioButton_2567012512_bindingFunctor {
        int operator()(RadioButton *self) const;
    };
    Qul::Private::Binding<RadioButton_2567012512_bindingFunctor, 0> item__2_implicitWidth_binding;
    struct text__y_anchor_bindingFunctor {
    int operator()(RadioButton *self) const;
};
    Qul::Private::Binding<text__y_anchor_bindingFunctor, 2> text__y_anchor_binding;
    struct RadioButton_641531737_bindingFunctor {
        Qul::PlatformInterface::Rgba32 operator()(RadioButton *self) const;
    };
    Qul::Private::Binding<RadioButton_641531737_bindingFunctor, 0> text__color_binding;
    struct RadioButton_350459312_bindingFunctor {
        Qul::Private::FontPointer operator()(RadioButton *self) const;
    };
    Qul::Private::Binding<RadioButton_350459312_bindingFunctor, 0> font_font_binding;
    struct RadioButton_4011053975_bindingFunctor {
        Qul::Private::String operator()(RadioButton *self) const;
    };
    Qul::Private::Binding<RadioButton_4011053975_bindingFunctor, 0> text__text_binding;
    struct RadioButton_1369550977_bindingFunctor {
        Qul::SharedImage operator()(RadioButton *self) const;
    };
    Qul::Private::Binding<RadioButton_1369550977_bindingFunctor, 0> image_source_binding;
    struct RadioButton_1494144167_bindingFunctor {
        int operator()(RadioButton *self) const;
    };
    Qul::Private::Binding<RadioButton_1494144167_bindingFunctor, 0> image_y_binding;
    struct RadioButton_1550939256_bindingFunctor {
        int operator()(RadioButton *self) const;
    };
    Qul::Private::Binding<RadioButton_1550939256_bindingFunctor, 0> image_x_binding;
    struct RadioButton_3560203182_bindingFunctor {
        int operator()(RadioButton *self) const;
    };
    Qul::Private::Binding<RadioButton_3560203182_bindingFunctor, 0> _implicitHeight_binding;
    struct RadioButton_2791446706_bindingFunctor {
        int operator()(RadioButton *self) const;
    };
    Qul::Private::Binding<RadioButton_2791446706_bindingFunctor, 0> _implicitWidth_binding;
};

} // namespace QtQuick
} // namespace Controls
} // namespace StyleDefault
