// This code is auto-generated by Qul's qmltocpp tool from the file 'Slider.qml'
// WARNING! All changes made in this file will be lost!
// NOTE: This generated API is to be considered implementation detail for Qul.
//       It may change from version to version and should not be relied upon.
#pragma once
#include "DefaultStyle.h"
#include <platforminterface/log.h>
#include <qul/image.h>
#include <qul/private/builtins.h>
#include <qul/private/controls/slidertemplate.h>
#include <qul/private/file.h>
#include <qul/private/items.h>
#include <qul/private/items/item.h>
#include <qul/private/qulrcc_lookup.h>
#include <qul/private/unicodestring.h>
#include <qul/signal.h>

namespace QtQuick {
namespace Controls {
namespace StyleDefault {

struct Slider : Qul::Private::Controls::Templates::Slider , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Controls::Templates::Slider  > {
    Slider();


    Qul::Property<Qul::Private::String> state;
    typedef Qul::Private::Items::BorderImage  borderimage_BorderImage;
    borderimage_BorderImage borderimage;
    typedef Qul::Private::Items::BorderImage  borderimage_2_BorderImage;
    borderimage_2_BorderImage borderimage_2;
    typedef Qul::Private::Items::Item  item__3_Item;
    item__3_Item item__3;
    typedef Qul::Private::Items::BorderImage  borderimage_3_BorderImage;
    borderimage_3_BorderImage borderimage_3;
    typedef Qul::Private::Items::BorderImage  borderimage_4_BorderImage;
    borderimage_4_BorderImage borderimage_4;
    typedef Qul::Private::Items::Item  item__4_Item;
    item__4_Item item__4;
    struct item__2_Item : Qul::Private::Items::Item , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Item  > {
        item__2_Item()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Item  >(this)
        {}
    } item__2;
    struct handleImage_Image : Qul::Private::Items::Image , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  > {
        handleImage_Image()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Image  >(this)
        {}
    } handleImage;
    struct item__Item : Qul::Private::Items::Item , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Item  > {
        item__Item()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Item  >(this)
        {}
    } item_;
    struct Slider_1848343518_bindingFunctor {
        int operator()(Slider *self) const;
    };
    Qul::Private::Binding<Slider_1848343518_bindingFunctor, 0> item__2_implicitHeight_binding;
    struct Slider_599813607_bindingFunctor {
        int operator()(Slider *self) const;
    };
    Qul::Private::Binding<Slider_599813607_bindingFunctor, 0> item__2_implicitWidth_binding;
    struct item__3_width_anchor_bindingFunctor {
    int operator()(Slider *self) const;
};
    Qul::Private::Binding<item__3_width_anchor_bindingFunctor, 1> item__3_width_anchor_binding;
    struct item__3_height_anchor_bindingFunctor {
    int operator()(Slider *self) const;
};
    Qul::Private::Binding<item__3_height_anchor_bindingFunctor, 1> item__3_height_anchor_binding;
    struct Slider_2197802071_bindingFunctor {
        bool operator()(Slider *self) const;
    };
    Qul::Private::Binding<Slider_2197802071_bindingFunctor, 0> item__3_visible_binding;
    struct Slider_2710219012_bindingFunctor {
        Qul::SharedImage operator()(Slider *self) const;
    };
    Qul::Private::Binding<Slider_2710219012_bindingFunctor, 0> borderimage_source_binding;
    struct borderimage_y_anchor_bindingFunctor {
    int operator()(Slider *self) const;
};
    Qul::Private::Binding<borderimage_y_anchor_bindingFunctor, 2> borderimage_y_anchor_binding;
    struct Slider_3758074988_bindingFunctor {
        int operator()(Slider *self) const;
    };
    Qul::Private::Binding<Slider_3758074988_bindingFunctor, 0> borderimage_width_binding;
    struct borderimage_2_y_anchor_bindingFunctor {
    int operator()(Slider *self) const;
};
    Qul::Private::Binding<borderimage_2_y_anchor_bindingFunctor, 2> borderimage_2_y_anchor_binding;
    struct Slider_1053273505_bindingFunctor {
        int operator()(Slider *self) const;
    };
    Qul::Private::Binding<Slider_1053273505_bindingFunctor, 0> borderimage_2_width_binding;
    struct Slider_2205357694_bindingFunctor {
        bool operator()(Slider *self) const;
    };
    Qul::Private::Binding<Slider_2205357694_bindingFunctor, 0> borderimage_2_visible_binding;
    struct item__4_width_anchor_bindingFunctor {
    int operator()(Slider *self) const;
};
    Qul::Private::Binding<item__4_width_anchor_bindingFunctor, 1> item__4_width_anchor_binding;
    struct item__4_height_anchor_bindingFunctor {
    int operator()(Slider *self) const;
};
    Qul::Private::Binding<item__4_height_anchor_bindingFunctor, 1> item__4_height_anchor_binding;
    struct Slider_2505692739_bindingFunctor {
        bool operator()(Slider *self) const;
    };
    Qul::Private::Binding<Slider_2505692739_bindingFunctor, 0> item__4_visible_binding;
    struct Slider_3535609003_bindingFunctor {
        Qul::SharedImage operator()(Slider *self) const;
    };
    Qul::Private::Binding<Slider_3535609003_bindingFunctor, 0> borderimage_3_source_binding;
    struct borderimage_3_x_anchor_bindingFunctor {
    int operator()(Slider *self) const;
};
    Qul::Private::Binding<borderimage_3_x_anchor_bindingFunctor, 2> borderimage_3_x_anchor_binding;
    struct Slider_989556812_bindingFunctor {
        int operator()(Slider *self) const;
    };
    Qul::Private::Binding<Slider_989556812_bindingFunctor, 0> borderimage_3_height_binding;
    struct borderimage_4_x_anchor_bindingFunctor {
    int operator()(Slider *self) const;
};
    Qul::Private::Binding<borderimage_4_x_anchor_bindingFunctor, 2> borderimage_4_x_anchor_binding;
    struct borderimage_4_y_anchor_bindingFunctor {
    int operator()(Slider *self) const;
};
    Qul::Private::Binding<borderimage_4_y_anchor_bindingFunctor, 2> borderimage_4_y_anchor_binding;
    struct Slider_679406184_bindingFunctor {
        int operator()(Slider *self) const;
    };
    Qul::Private::Binding<Slider_679406184_bindingFunctor, 0> borderimage_4_height_binding;
    struct Slider_1130741331_bindingFunctor {
        bool operator()(Slider *self) const;
    };
    Qul::Private::Binding<Slider_1130741331_bindingFunctor, 0> borderimage_4_visible_binding;
    struct Slider_2541129590_bindingFunctor {
        int operator()(Slider *self) const;
    };
    Qul::Private::Binding<Slider_2541129590_bindingFunctor, 0> item__implicitHeight_binding;
    struct Slider_866776488_bindingFunctor {
        int operator()(Slider *self) const;
    };
    Qul::Private::Binding<Slider_866776488_bindingFunctor, 0> item__implicitWidth_binding;
    struct Slider_1494971444_bindingFunctor {
        int operator()(Slider *self) const;
    };
    Qul::Private::Binding<Slider_1494971444_bindingFunctor, 0> item__y_binding;
    struct Slider_334686001_bindingFunctor {
        int operator()(Slider *self) const;
    };
    Qul::Private::Binding<Slider_334686001_bindingFunctor, 0> item__x_binding;
    struct handleImage_x_anchor_bindingFunctor {
    int operator()(Slider *self) const;
};
    Qul::Private::Binding<handleImage_x_anchor_bindingFunctor, 2> handleImage_x_anchor_binding;
    struct handleImage_y_anchor_bindingFunctor {
    int operator()(Slider *self) const;
};
    Qul::Private::Binding<handleImage_y_anchor_bindingFunctor, 2> handleImage_y_anchor_binding;
    struct Slider_628559372_bindingFunctor {
        Qul::SharedImage operator()(Slider *self) const;
    };
    Qul::Private::Binding<Slider_628559372_bindingFunctor, 0> handleImage_source_binding;
    struct Slider_213537238_bindingFunctor {
        int operator()(Slider *self) const;
    };
    Qul::Private::Binding<Slider_213537238_bindingFunctor, 0> _implicitHeight_binding;
    struct Slider_2656902717_bindingFunctor {
        int operator()(Slider *self) const;
    };
    Qul::Private::Binding<Slider_2656902717_bindingFunctor, 0> _implicitWidth_binding;
};

} // namespace QtQuick
} // namespace Controls
} // namespace StyleDefault
