// This code is auto-generated by Qul's qmltocpp tool from the file 'Slider.qml'
// WARNING! All changes made in this file will be lost!
#include "Slider.h"
#include <qul/private/graphicsdevice.h>
#include <qul/private/filecache.h>

extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_slider_2Dbackground_2659112635278775450_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_slider_2Dbackground_2Ddisabled_9429117108122117601_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_slider_2Dprogress_12840436375357393042_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_slider_2Dbackground_2Dvertical_8489368424421342831_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_slider_2Dbackground_2Ddisabled_2Dvertical_9928093480218240469_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_slider_2Dprogress_2Dvertical_17367687796409029701_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_slider_2Dhandle_2Dpressed_4859009982694974880_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_slider_2Dhandle_4014514759752923839_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_slider_2Dhandle_2Ddisabled_2Dpressed_7769495367122408564_handle;
extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_slider_2Dhandle_2Ddisabled_9677515102556419862_handle;
static const Qul::Private::String qulCurrentFileDir(".", 1);
namespace QtQuick {
namespace Controls {
namespace StyleDefault {
extern Qul::Private::Items::ItemBase *loaderItemAllocator(const Qul::Private::String &uri, const Qul::Private::String &currentFileDir);

} // namespace QtQuick
} // namespace Controls
} // namespace StyleDefault
namespace Qul { namespace Private {
Qul::Property<int> &translationIndexProperty_da39a3ee5e6b4b0d3255bfef95601890afd80709();
extern const uint32_t *qul_translation_offsets_c28c1f68cd4b495375f9d684e2ae049fdc3b8836();
extern const uint8_t *qul_translations_c28c1f68cd4b495375f9d684e2ae049fdc3b8836();
}}

namespace QtQuick {
namespace Controls {
namespace StyleDefault {

namespace {
#if defined(QUL_CC_IAR)
#pragma diag_suppress=Pe177 // declared but never referenced
#elif defined(QUL_CC_GNU)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-function"
#endif
static Qul::Property<int> &translationIndexProperty() { return Qul::Private::translationIndexProperty_da39a3ee5e6b4b0d3255bfef95601890afd80709(); }
static int translationIndex() { return translationIndexProperty().value(); }
static const char *qul_translation(int entry) {
    const size_t translationLanguageCount = 1;
    const uint32_t *offsets = Qul::Private::qul_translation_offsets_c28c1f68cd4b495375f9d684e2ae049fdc3b8836();
    const uint8_t *translations = Qul::Private::qul_translations_c28c1f68cd4b495375f9d684e2ae049fdc3b8836();
    return reinterpret_cast<const char *>(&translations[offsets[entry * translationLanguageCount + translationIndex()]]);
}
#if defined(QUL_CC_IAR)
#pragma diag_default=Pe177 // declared but never referenced
#elif defined(QUL_CC_GNU)
#pragma GCC diagnostic pop
#endif
}


int Slider::Slider_1848343518_bindingFunctor::operator()(Slider *self) const
{
    (void) self;
    int r2_1;
    bool r2_3;
    QUL_DECL_UNUSED Slider * r2 = NULL;
    QUL_DECL_UNUSED Qul::Private::Builtins::GlobalQtObject::Orientation r2__Horizontal;
    QUL_DECL_UNUSED Qul::Private::Builtins::GlobalQtObject::Orientation r7__orientation;
    // implicitHeight: control.orientation == Qt.Horizontal ? 3 : 200
    // line 70  "Slider.qml"
    r2 = self;
    r2__Horizontal = r2->orientation.value();
    r7__orientation = r2__Horizontal;
    r2__Horizontal = Qul::Private::Builtins::GlobalQtObject::Horizontal;
    r2_3 = Qul::Private::testEqual(r7__orientation, r2__Horizontal);
    if (!r2_3) goto label_0;;
    r2_1 = 3;
    goto label_1;;
    label_0:;
    r2_1 = 200;
    label_1:;
    return r2_1;
    
}
int Slider::Slider_599813607_bindingFunctor::operator()(Slider *self) const
{
    (void) self;
    int r2_1;
    bool r2_3;
    QUL_DECL_UNUSED Slider * r2 = NULL;
    QUL_DECL_UNUSED Qul::Private::Builtins::GlobalQtObject::Orientation r2__Horizontal;
    QUL_DECL_UNUSED Qul::Private::Builtins::GlobalQtObject::Orientation r7__orientation;
    // implicitWidth: control.orientation == Qt.Horizontal ? 200 : 3
    // line 69  "Slider.qml"
    r2 = self;
    r2__Horizontal = r2->orientation.value();
    r7__orientation = r2__Horizontal;
    r2__Horizontal = Qul::Private::Builtins::GlobalQtObject::Horizontal;
    r2_3 = Qul::Private::testEqual(r7__orientation, r2__Horizontal);
    if (!r2_3) goto label_0;;
    r2_1 = 200;
    goto label_1;;
    label_0:;
    r2_1 = 3;
    label_1:;
    return r2_1;
    
}
int Slider::item__3_width_anchor_bindingFunctor::operator()(Slider *self) const {
        return int(self->item__2.width.value());
}
int Slider::item__3_height_anchor_bindingFunctor::operator()(Slider *self) const {
        return int(self->item__2.height.value());
}
bool Slider::Slider_2197802071_bindingFunctor::operator()(Slider *self) const
{
    (void) self;
    bool r2_2;
    QUL_DECL_UNUSED Slider * r2 = NULL;
    QUL_DECL_UNUSED Qul::Private::Builtins::GlobalQtObject::Orientation r2__Horizontal;
    QUL_DECL_UNUSED Qul::Private::Builtins::GlobalQtObject::Orientation r7__orientation;
    // visible: control.orientation == Qt.Horizontal
    // line 73  "Slider.qml"
    r2 = self;
    r2__Horizontal = r2->orientation.value();
    r7__orientation = r2__Horizontal;
    r2__Horizontal = Qul::Private::Builtins::GlobalQtObject::Horizontal;
    r2_2 = Qul::Private::testEqual(r7__orientation, r2__Horizontal);
    return r2_2;
    
}
Qul::SharedImage Slider::Slider_2710219012_bindingFunctor::operator()(Slider *self) const
{
    (void) self;
    bool r2__enabled;
    QUL_DECL_UNUSED Slider * r2 = NULL;
    QUL_DECL_UNUSED Qul::Private::String r2_1;
    /*
    source: control.enabled
    ? "qrc:/images/slider-background.png"
    */
    // line 82  "Slider.qml"
    r2 = self;
    r2__enabled = r2->enabled.value();
    if (!r2__enabled) goto label_0;;
    r2_1 = Qul::Private::String(Qul::Private::ImageIdValue::create("qrc:/images/slider-background.png", qul_rasterBuffer_slider_2Dbackground_2659112635278775450_handle), 33);
    goto label_1;;
    label_0:;
    r2_1 = Qul::Private::String(Qul::Private::ImageIdValue::create("qrc:/images/slider-background-disabled.png", qul_rasterBuffer_slider_2Dbackground_2Ddisabled_9429117108122117601_handle), 42);
    label_1:;
    // : "qrc:/images/slider-background-disabled.png"
    // line 84  "Slider.qml"
    return Qul::Private::findImageForString(r2_1);
    
}
int Slider::borderimage_y_anchor_bindingFunctor::operator()(Slider *self) const {
        return int((int(self->item__3.height.value()) + 1)/2 - ((self->borderimage.height.value())/2.0));
}
int Slider::Slider_3758074988_bindingFunctor::operator()(Slider *self) const
{
    (void) self;
    int r2__width;
    QUL_DECL_UNUSED item__3_Item * r2 = NULL;
    // width: parent.width
    // line 77  "Slider.qml"
    r2 = self->borderimage.parent<item__3_Item >();
    r2__width = r2->width.value();
    return r2__width;
    
}
int Slider::borderimage_2_y_anchor_bindingFunctor::operator()(Slider *self) const {
        return int((int(self->item__3.height.value()) + 1)/2 - ((self->borderimage_2.height.value())/2.0));
}
int Slider::Slider_1053273505_bindingFunctor::operator()(Slider *self) const
{
    (void) self;
    int r8__implicitWidth;
    int r2__implicitWidth;
    Qul::qreal r2_1;
    QUL_DECL_UNUSED Qul::Private::Items::ItemBase * r2 = NULL;
    int r7__x;
    // width: handle.x + (handle.implicitWidth / 2)
    // line 89  "Slider.qml"
    r2 = self->handle.value();
    r2__implicitWidth = r2->x.value();
    r7__x = r2__implicitWidth;
    r2 = self->handle.value();
    r2__implicitWidth = r2->itemExtraProperties->implicitWidth.value();
    r8__implicitWidth = r2__implicitWidth;
    r2__implicitWidth = 2;
    r2_1 = Qul::qreal(r8__implicitWidth) / r2__implicitWidth;
    r2_1 = r7__x + r2_1;
    return int(r2_1);
    
}
bool Slider::Slider_2205357694_bindingFunctor::operator()(Slider *self) const
{
    (void) self;
    bool r2_1;
    int r2_3;
    QUL_DECL_UNUSED Slider * r2 = NULL;
    Qul::qreal r2__visualPosition;
    Qul::qreal r7__visualPosition;
    // visible: control.enabled && control.visualPosition > 0
    // line 88  "Slider.qml"
    r2 = self;
    r2_1 = r2->enabled.value();
    if (!r2_1) {
    goto label_0;};
    r2 = self;
    r2__visualPosition = r2->visualPosition.value();
    r7__visualPosition = r2__visualPosition;
    r2_3 = 0;
    r2_1 = r7__visualPosition > r2_3;
    {
    }
    label_0:;
    return r2_1;
    
}
int Slider::item__4_width_anchor_bindingFunctor::operator()(Slider *self) const {
        return int(self->item__2.width.value());
}
int Slider::item__4_height_anchor_bindingFunctor::operator()(Slider *self) const {
        return int(self->item__2.height.value());
}
bool Slider::Slider_2505692739_bindingFunctor::operator()(Slider *self) const
{
    (void) self;
    bool r2_2;
    QUL_DECL_UNUSED Slider * r2 = NULL;
    QUL_DECL_UNUSED Qul::Private::Builtins::GlobalQtObject::Orientation r2__Vertical;
    QUL_DECL_UNUSED Qul::Private::Builtins::GlobalQtObject::Orientation r7__orientation;
    // visible: control.orientation == Qt.Vertical
    // line 99  "Slider.qml"
    r2 = self;
    r2__Vertical = r2->orientation.value();
    r7__orientation = r2__Vertical;
    r2__Vertical = Qul::Private::Builtins::GlobalQtObject::Vertical;
    r2_2 = Qul::Private::testEqual(r7__orientation, r2__Vertical);
    return r2_2;
    
}
Qul::SharedImage Slider::Slider_3535609003_bindingFunctor::operator()(Slider *self) const
{
    (void) self;
    bool r2__enabled;
    QUL_DECL_UNUSED Slider * r2 = NULL;
    QUL_DECL_UNUSED Qul::Private::String r2_1;
    /*
    source: control.enabled
    ? "qrc:/images/slider-background-vertical.png"
    */
    // line 108  "Slider.qml"
    r2 = self;
    r2__enabled = r2->enabled.value();
    if (!r2__enabled) goto label_0;;
    r2_1 = Qul::Private::String(Qul::Private::ImageIdValue::create("qrc:/images/slider-background-vertical.png", qul_rasterBuffer_slider_2Dbackground_2Dvertical_8489368424421342831_handle), 42);
    goto label_1;;
    label_0:;
    r2_1 = Qul::Private::String(Qul::Private::ImageIdValue::create("qrc:/images/slider-background-disabled-vertical.png", qul_rasterBuffer_slider_2Dbackground_2Ddisabled_2Dvertical_9928093480218240469_handle), 51);
    label_1:;
    // : "qrc:/images/slider-background-disabled-vertical.png"
    // line 110  "Slider.qml"
    return Qul::Private::findImageForString(r2_1);
    
}
int Slider::borderimage_3_x_anchor_bindingFunctor::operator()(Slider *self) const {
        return int((int(self->item__4.width.value()) + 1)/2 - ((self->borderimage_3.width.value())/2.0));
}
int Slider::Slider_989556812_bindingFunctor::operator()(Slider *self) const
{
    (void) self;
    int r2__height;
    QUL_DECL_UNUSED item__4_Item * r2 = NULL;
    // height: parent.height
    // line 103  "Slider.qml"
    r2 = self->borderimage_3.parent<item__4_Item >();
    r2__height = r2->height.value();
    return r2__height;
    
}
int Slider::borderimage_4_x_anchor_bindingFunctor::operator()(Slider *self) const {
        return int((int(self->item__4.width.value()) + 1)/2 - ((self->borderimage_4.width.value())/2.0));
}
int Slider::borderimage_4_y_anchor_bindingFunctor::operator()(Slider *self) const {
        return int(self->item__4.height.value() - (self->borderimage_4.height.value()));
}
int Slider::Slider_679406184_bindingFunctor::operator()(Slider *self) const
{
    (void) self;
    int r8;
    int r2_1;
    Qul::qreal r2_2;
    QUL_DECL_UNUSED item__4_Item * r2 = NULL;
    QUL_DECL_UNUSED Qul::Private::Items::ItemBase * r2_3 = NULL;
    int r9__implicitHeight;
    int r7__height;
    // height: parent.height - handle.y - (handle.implicitHeight / 2)
    // line 115  "Slider.qml"
    r2 = self->borderimage_4.parent<item__4_Item >();
    r2_1 = r2->height.value();
    r7__height = r2_1;
    r2_3 = self->handle.value();
    r2_1 = r2_3->y.value();
    r2_1 = r7__height - r2_1;
    r8 = r2_1;
    r2_3 = self->handle.value();
    r2_1 = r2_3->itemExtraProperties->implicitHeight.value();
    r9__implicitHeight = r2_1;
    r2_1 = 2;
    r2_2 = Qul::qreal(r9__implicitHeight) / r2_1;
    r2_2 = r8 - r2_2;
    return int(r2_2);
    
}
bool Slider::Slider_1130741331_bindingFunctor::operator()(Slider *self) const
{
    (void) self;
    bool r2_1;
    int r2_3;
    QUL_DECL_UNUSED Slider * r2 = NULL;
    Qul::qreal r2__visualPosition;
    Qul::qreal r7__visualPosition;
    // visible: control.enabled && control.visualPosition < 1
    // line 114  "Slider.qml"
    r2 = self;
    r2_1 = r2->enabled.value();
    if (!r2_1) {
    goto label_0;};
    r2 = self;
    r2__visualPosition = r2->visualPosition.value();
    r7__visualPosition = r2__visualPosition;
    r2_3 = 1;
    r2_1 = r7__visualPosition < r2_3;
    {
    }
    label_0:;
    return r2_1;
    
}
int Slider::Slider_2541129590_bindingFunctor::operator()(Slider *self) const
{
    (void) self;
    int r2_1;
    QUL_DECL_UNUSED handleImage_Image * r2 = NULL;
    int r7__implicitHeight;
    // implicitHeight: handleImage.implicitHeight - 20
    // line 50  "Slider.qml"
    r2 = &self->handleImage;
    r2_1 = r2->itemExtraProperties->implicitHeight.value();
    r7__implicitHeight = r2_1;
    r2_1 = 20;
    r2_1 = r7__implicitHeight - r2_1;
    return r2_1;
    
}
int Slider::Slider_866776488_bindingFunctor::operator()(Slider *self) const
{
    (void) self;
    int r2_1;
    QUL_DECL_UNUSED handleImage_Image * r2 = NULL;
    int r7__implicitWidth;
    // implicitWidth: handleImage.implicitWidth - 20
    // line 48  "Slider.qml"
    r2 = &self->handleImage;
    r2_1 = r2->itemExtraProperties->implicitWidth.value();
    r7__implicitWidth = r2_1;
    r2_1 = 20;
    r2_1 = r7__implicitWidth - r2_1;
    return r2_1;
    
}
int Slider::Slider_1494971444_bindingFunctor::operator()(Slider *self) const
{
    (void) self;
    int r9__availableHeight;
    QUL_DECL_UNUSED Qul::Private::Builtins::GlobalQtObject::Orientation r7__orientation;
    Qul::qreal r13;
    Qul::qreal r8__visualPosition;
    int r2__height;
    QUL_DECL_UNUSED Slider * r2 = NULL;
    bool r2_6;
    QUL_DECL_UNUSED handleImage_Image * r2_3 = NULL;
    Qul::qreal r2_2;
    QUL_DECL_UNUSED Qul::Private::Builtins::GlobalQtObject::Orientation r2__Vertical;
    int r12__height;
    int r14;
    int r10__implicitHeight;
    Qul::qreal r11;
    // y: control.orientation == Qt.Vertical ? control.visualPosition * (parent.availableHeight - handleImage.implicitHeight / 2) + parent.topInset : (parent.height / 2 - implicitHeight / 2)
    // line 46  "Slider.qml"
    r2 = self;
    r2__Vertical = r2->orientation.value();
    r7__orientation = r2__Vertical;
    r2__Vertical = Qul::Private::Builtins::GlobalQtObject::Vertical;
    r2_6 = Qul::Private::testEqual(r7__orientation, r2__Vertical);
    if (!r2_6) {
    goto label_0;};
    r2 = self;
    r2_2 = r2->visualPosition.value();
    r8__visualPosition = r2_2;
    r2 = self->item_.parent<Slider >();
    r2__height = r2->availableHeight.value();
    r9__availableHeight = r2__height;
    r2_3 = &self->handleImage;
    r2__height = r2_3->itemExtraProperties->implicitHeight.value();
    r10__implicitHeight = r2__height;
    r2__height = 2;
    r2_2 = Qul::qreal(r10__implicitHeight) / r2__height;
    r2_2 = r9__availableHeight - r2_2;
    r2_2 = r8__visualPosition * r2_2;
    r11 = r2_2;
    r2 = self->item_.parent<Slider >();
    r2__height = r2->topInset.value();
    r2_2 = r11 + r2__height;
    {
    goto label_1;};
    {
    }
    label_0:;
    r2 = self->item_.parent<Slider >();
    r2__height = r2->height.value();
    r12__height = r2__height;
    r2__height = 2;
    r2_2 = Qul::qreal(r12__height) / r2__height;
    r13 = r2_2;
    r2__height = self->item_.itemExtraProperties->implicitHeight.value();
    r14 = r2__height;
    r2__height = 2;
    r2_2 = Qul::qreal(r14) / r2__height;
    r2_2 = r13 - r2_2;
    {
    }
    label_1:;
    return int(r2_2);
    
}
int Slider::Slider_334686001_bindingFunctor::operator()(Slider *self) const
{
    (void) self;
    int r9__availableWidth;
    QUL_DECL_UNUSED Qul::Private::Builtins::GlobalQtObject::Orientation r7__orientation;
    Qul::qreal r13;
    Qul::qreal r8__visualPosition;
    int r2__width;
    QUL_DECL_UNUSED Slider * r2 = NULL;
    bool r2_6;
    QUL_DECL_UNUSED handleImage_Image * r2_3 = NULL;
    Qul::qreal r2_2;
    QUL_DECL_UNUSED Qul::Private::Builtins::GlobalQtObject::Orientation r2__Horizontal;
    int r12__width;
    int r14;
    int r10__implicitWidth;
    Qul::qreal r11;
    // x: control.orientation == Qt.Horizontal ? control.visualPosition * (parent.availableWidth - handleImage.implicitWidth / 2) + parent.leftInset : (parent.width / 2 - implicitWidth / 2)
    // line 45  "Slider.qml"
    r2 = self;
    r2__Horizontal = r2->orientation.value();
    r7__orientation = r2__Horizontal;
    r2__Horizontal = Qul::Private::Builtins::GlobalQtObject::Horizontal;
    r2_6 = Qul::Private::testEqual(r7__orientation, r2__Horizontal);
    if (!r2_6) {
    goto label_0;};
    r2 = self;
    r2_2 = r2->visualPosition.value();
    r8__visualPosition = r2_2;
    r2 = self->item_.parent<Slider >();
    r2__width = r2->availableWidth.value();
    r9__availableWidth = r2__width;
    r2_3 = &self->handleImage;
    r2__width = r2_3->itemExtraProperties->implicitWidth.value();
    r10__implicitWidth = r2__width;
    r2__width = 2;
    r2_2 = Qul::qreal(r10__implicitWidth) / r2__width;
    r2_2 = r9__availableWidth - r2_2;
    r2_2 = r8__visualPosition * r2_2;
    r11 = r2_2;
    r2 = self->item_.parent<Slider >();
    r2__width = r2->leftInset.value();
    r2_2 = r11 + r2__width;
    {
    goto label_1;};
    {
    }
    label_0:;
    r2 = self->item_.parent<Slider >();
    r2__width = r2->width.value();
    r12__width = r2__width;
    r2__width = 2;
    r2_2 = Qul::qreal(r12__width) / r2__width;
    r13 = r2_2;
    r2__width = self->item_.itemExtraProperties->implicitWidth.value();
    r14 = r2__width;
    r2__width = 2;
    r2_2 = Qul::qreal(r14) / r2__width;
    r2_2 = r13 - r2_2;
    {
    }
    label_1:;
    return int(r2_2);
    
}
int Slider::handleImage_x_anchor_bindingFunctor::operator()(Slider *self) const {
        return int((int(self->item_.width.value()) + 1)/2 - ((self->handleImage.width.value())/2.0));
}
int Slider::handleImage_y_anchor_bindingFunctor::operator()(Slider *self) const {
        return int((int(self->item_.height.value()) + 1)/2 + (5) - ((self->handleImage.height.value())/2.0));
}
Qul::SharedImage Slider::Slider_628559372_bindingFunctor::operator()(Slider *self) const
{
    (void) self;
    bool r2__pressed;
    QUL_DECL_UNUSED Slider * r2 = NULL;
    QUL_DECL_UNUSED Qul::Private::String r2_1;
    // source: control.enabled
    // line 54  "Slider.qml"
    r2 = self;
    r2__pressed = r2->enabled.value();
    if (!r2__pressed) goto label_0;;
    r2 = self;
    /*
    ? control.pressed
    ? "qrc:/images/slider-handle-pressed.png"
    : "qrc:/images/slider-handle.png"
    */
    // line 55  "Slider.qml"
    r2__pressed = r2->pressed.value();
    if (!r2__pressed) goto label_1;;
    r2_1 = Qul::Private::String(Qul::Private::ImageIdValue::create("qrc:/images/slider-handle-pressed.png", qul_rasterBuffer_slider_2Dhandle_2Dpressed_4859009982694974880_handle), 37);
    goto label_2;;
    label_1:;
    r2_1 = Qul::Private::String(Qul::Private::ImageIdValue::create("qrc:/images/slider-handle.png", qul_rasterBuffer_slider_2Dhandle_4014514759752923839_handle), 29);
    label_2:;
    goto label_3;;
    label_0:;
    r2 = self;
    /*
    : control.pressed
    ? "qrc:/images/slider-handle-disabled-pressed.png"
    */
    // line 58  "Slider.qml"
    r2__pressed = r2->pressed.value();
    if (!r2__pressed) goto label_4;;
    r2_1 = Qul::Private::String(Qul::Private::ImageIdValue::create("qrc:/images/slider-handle-disabled-pressed.png", qul_rasterBuffer_slider_2Dhandle_2Ddisabled_2Dpressed_7769495367122408564_handle), 46);
    goto label_3;;
    label_4:;
    r2_1 = Qul::Private::String(Qul::Private::ImageIdValue::create("qrc:/images/slider-handle-disabled.png", qul_rasterBuffer_slider_2Dhandle_2Ddisabled_9677515102556419862_handle), 38);
    label_3:;
    // : "qrc:/images/slider-handle-disabled.png"
    // line 60  "Slider.qml"
    return Qul::Private::findImageForString(r2_1);
    
}
int Slider::Slider_213537238_bindingFunctor::operator()(Slider *self) const
{
    (void) self;
    int r2_2;
    Qul::qreal r2_1;
    QUL_DECL_UNUSED Qul::Private::Builtins::Math * r2 = NULL;
    QUL_DECL_UNUSED Qul::Private::Items::ItemBase * r2_3 = NULL;
    int r10;
    int r12;
    int r11;
    QUL_DECL_UNUSED Qul::Private::Builtins::Math * r7 = NULL;
    int r13;
    // implicitHeight: Math.max((background ? background.implicitHeight : 0) + topInset + bottomInset,
    // line 30  "Slider.qml"
    r2 = &Qul::Private::Builtins::Math ::instance();
    r7 = r2;
    r2_3 = self->background.value();
    if (!r2_3) goto label_0;;
    r2_3 = self->background.value();
    r2_2 = r2_3->itemExtraProperties->implicitHeight.value();
    goto label_1;;
    label_0:;
    r2_2 = 0;
    label_1:;
    r12 = r2_2;
    r2_2 = self->topInset.value();
    r2_2 = r12 + r2_2;
    r13 = r2_2;
    r2_2 = self->bottomInset.value();
    r2_2 = r13 + r2_2;
    r10 = r2_2;
    // (handle ? handle.implicitHeight : 0) + topPadding + bottomPadding)
    // line 31  "Slider.qml"
    r2_3 = self->handle.value();
    if (!r2_3) goto label_2;;
    r2_3 = self->handle.value();
    r2_2 = r2_3->itemExtraProperties->implicitHeight.value();
    goto label_3;;
    label_2:;
    r2_2 = 0;
    label_3:;
    r12 = r2_2;
    r2_2 = self->topPadding.value();
    r2_2 = r12 + r2_2;
    r13 = r2_2;
    r2_2 = self->bottomPadding.value();
    r2_2 = r13 + r2_2;
    r11 = r2_2;
    r2_1 = r7->max(r10, r11);
    return int(r2_1);
    
}
int Slider::Slider_2656902717_bindingFunctor::operator()(Slider *self) const
{
    (void) self;
    int r2_2;
    Qul::qreal r2_1;
    QUL_DECL_UNUSED Qul::Private::Builtins::Math * r2 = NULL;
    QUL_DECL_UNUSED Qul::Private::Items::ItemBase * r2_3 = NULL;
    int r10;
    int r12;
    int r11;
    QUL_DECL_UNUSED Qul::Private::Builtins::Math * r7 = NULL;
    int r13;
    // implicitWidth: Math.max((background ? background.implicitWidth : 0) + leftInset + rightInset,
    // line 28  "Slider.qml"
    r2 = &Qul::Private::Builtins::Math ::instance();
    r7 = r2;
    r2_3 = self->background.value();
    if (!r2_3) goto label_0;;
    r2_3 = self->background.value();
    r2_2 = r2_3->itemExtraProperties->implicitWidth.value();
    goto label_1;;
    label_0:;
    r2_2 = 0;
    label_1:;
    r12 = r2_2;
    r2_2 = self->leftInset.value();
    r2_2 = r12 + r2_2;
    r13 = r2_2;
    r2_2 = self->rightInset.value();
    r2_2 = r13 + r2_2;
    r10 = r2_2;
    // (handle ? handle.implicitWidth : 0) + leftPadding + rightPadding)
    // line 29  "Slider.qml"
    r2_3 = self->handle.value();
    if (!r2_3) goto label_2;;
    r2_3 = self->handle.value();
    r2_2 = r2_3->itemExtraProperties->implicitWidth.value();
    goto label_3;;
    label_2:;
    r2_2 = 0;
    label_3:;
    r12 = r2_2;
    r2_2 = self->leftPadding.value();
    r2_2 = r12 + r2_2;
    r13 = r2_2;
    r2_2 = self->rightPadding.value();
    r2_2 = r13 + r2_2;
    r11 = r2_2;
    r2_1 = r7->max(r10, r11);
    return int(r2_1);
    
}

Slider::Slider()

    : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Controls::Templates::Slider  >(this)
    , item__2_implicitHeight_binding(Slider_1848343518_bindingFunctor())
    , item__2_implicitWidth_binding(Slider_599813607_bindingFunctor())
    , item__3_width_anchor_binding(item__3_width_anchor_bindingFunctor())
    , item__3_height_anchor_binding(item__3_height_anchor_bindingFunctor())
    , item__3_visible_binding(Slider_2197802071_bindingFunctor())
    , borderimage_source_binding(Slider_2710219012_bindingFunctor())
    , borderimage_y_anchor_binding(borderimage_y_anchor_bindingFunctor())
    , borderimage_width_binding(Slider_3758074988_bindingFunctor())
    , borderimage_2_y_anchor_binding(borderimage_2_y_anchor_bindingFunctor())
    , borderimage_2_width_binding(Slider_1053273505_bindingFunctor())
    , borderimage_2_visible_binding(Slider_2205357694_bindingFunctor())
    , item__4_width_anchor_binding(item__4_width_anchor_bindingFunctor())
    , item__4_height_anchor_binding(item__4_height_anchor_bindingFunctor())
    , item__4_visible_binding(Slider_2505692739_bindingFunctor())
    , borderimage_3_source_binding(Slider_3535609003_bindingFunctor())
    , borderimage_3_x_anchor_binding(borderimage_3_x_anchor_bindingFunctor())
    , borderimage_3_height_binding(Slider_989556812_bindingFunctor())
    , borderimage_4_x_anchor_binding(borderimage_4_x_anchor_bindingFunctor())
    , borderimage_4_y_anchor_binding(borderimage_4_y_anchor_bindingFunctor())
    , borderimage_4_height_binding(Slider_679406184_bindingFunctor())
    , borderimage_4_visible_binding(Slider_1130741331_bindingFunctor())
    , item__implicitHeight_binding(Slider_2541129590_bindingFunctor())
    , item__implicitWidth_binding(Slider_866776488_bindingFunctor())
    , item__y_binding(Slider_1494971444_bindingFunctor())
    , item__x_binding(Slider_334686001_bindingFunctor())
    , handleImage_x_anchor_binding(handleImage_x_anchor_bindingFunctor())
    , handleImage_y_anchor_binding(handleImage_y_anchor_bindingFunctor())
    , handleImage_source_binding(Slider_628559372_bindingFunctor())
    , _implicitHeight_binding(Slider_213537238_bindingFunctor())
    , _implicitWidth_binding(Slider_2656902717_bindingFunctor())
{
    item__2_implicitHeight_binding.init<Slider, &Slider::item__2_implicitHeight_binding>(item__2.itemExtraProperties->implicitHeight);
    // implicitHeight: control.orientation == Qt.Horizontal ? 3 : 200
    // line 70  "Slider.qml"
    item__2.itemExtraProperties->implicitHeight.setBinding (&item__2_implicitHeight_binding);
    item__2_implicitWidth_binding.init<Slider, &Slider::item__2_implicitWidth_binding>(item__2.itemExtraProperties->implicitWidth);
    // implicitWidth: control.orientation == Qt.Horizontal ? 200 : 3
    // line 69  "Slider.qml"
    item__2.itemExtraProperties->implicitWidth.setBinding (&item__2_implicitWidth_binding);
    // Item {
    // line 72  "Slider.qml"
    appendChild(&this->item__2, &item__3);
    item__3.x.setValue(int());
    item__3_width_anchor_binding.init<Slider, &Slider::item__3_width_anchor_binding>(item__3.width);
    item__3.width.setBinding(&item__3_width_anchor_binding);
    item__3.y.setValue(int());
    item__3_height_anchor_binding.init<Slider, &Slider::item__3_height_anchor_binding>(item__3.height);
    item__3.height.setBinding(&item__3_height_anchor_binding);
    item__3_visible_binding.init<Slider, &Slider::item__3_visible_binding>(item__3.visible);
    // visible: control.orientation == Qt.Horizontal
    // line 73  "Slider.qml"
    item__3.visible.setBinding (&item__3_visible_binding);
    // BorderImage {
    // line 76  "Slider.qml"
    appendChild(&this->item__3, &borderimage);
    borderimage_source_binding.init<Slider, &Slider::borderimage_source_binding>(borderimage.source);
    // source: control.enabled
    // line 82  "Slider.qml"
    borderimage.source.setBinding (&borderimage_source_binding);
    // border.right: 4
    // line 81  "Slider.qml"
    borderimage.border.right.setValue(4);
    // border.left: 4
    // line 80  "Slider.qml"
    borderimage.border.left.setValue(4);
    borderimage_y_anchor_binding.init<Slider, &Slider::borderimage_y_anchor_binding>(borderimage.y);
    borderimage.y.setBinding(&borderimage_y_anchor_binding);
    // height: 9
    // line 78  "Slider.qml"
    borderimage.height.setValue(9);
    borderimage_width_binding.init<Slider, &Slider::borderimage_width_binding>(borderimage.width);
    // width: parent.width
    // line 77  "Slider.qml"
    borderimage.width.setBinding (&borderimage_width_binding);
    // BorderImage {
    // line 87  "Slider.qml"
    appendChild(&this->item__3, &borderimage_2);
    // source: "qrc:/images/slider-progress.png"
    // line 94  "Slider.qml"
    borderimage_2.source.setValue(Qul::Private::ImagePrivate::fromRasterBuffer(qul_rasterBuffer_slider_2Dprogress_12840436375357393042_handle));
    // border.right: 4
    // line 93  "Slider.qml"
    borderimage_2.border.right.setValue(4);
    // border.left: 4
    // line 92  "Slider.qml"
    borderimage_2.border.left.setValue(4);
    borderimage_2_y_anchor_binding.init<Slider, &Slider::borderimage_2_y_anchor_binding>(borderimage_2.y);
    borderimage_2.y.setBinding(&borderimage_2_y_anchor_binding);
    // height: 9
    // line 90  "Slider.qml"
    borderimage_2.height.setValue(9);
    borderimage_2_width_binding.init<Slider, &Slider::borderimage_2_width_binding>(borderimage_2.width);
    // width: handle.x + (handle.implicitWidth / 2)
    // line 89  "Slider.qml"
    borderimage_2.width.setBinding (&borderimage_2_width_binding);
    borderimage_2_visible_binding.init<Slider, &Slider::borderimage_2_visible_binding>(borderimage_2.visible);
    // visible: control.enabled && control.visualPosition > 0
    // line 88  "Slider.qml"
    borderimage_2.visible.setBinding (&borderimage_2_visible_binding);
    // Item {
    // line 98  "Slider.qml"
    appendChild(&this->item__2, &item__4);
    item__4.x.setValue(int());
    item__4_width_anchor_binding.init<Slider, &Slider::item__4_width_anchor_binding>(item__4.width);
    item__4.width.setBinding(&item__4_width_anchor_binding);
    item__4.y.setValue(int());
    item__4_height_anchor_binding.init<Slider, &Slider::item__4_height_anchor_binding>(item__4.height);
    item__4.height.setBinding(&item__4_height_anchor_binding);
    item__4_visible_binding.init<Slider, &Slider::item__4_visible_binding>(item__4.visible);
    // visible: control.orientation == Qt.Vertical
    // line 99  "Slider.qml"
    item__4.visible.setBinding (&item__4_visible_binding);
    // BorderImage {
    // line 102  "Slider.qml"
    appendChild(&this->item__4, &borderimage_3);
    borderimage_3_source_binding.init<Slider, &Slider::borderimage_3_source_binding>(borderimage_3.source);
    // source: control.enabled
    // line 108  "Slider.qml"
    borderimage_3.source.setBinding (&borderimage_3_source_binding);
    // border.bottom: 4
    // line 107  "Slider.qml"
    borderimage_3.border.bottom.setValue(4);
    // border.top: 4
    // line 106  "Slider.qml"
    borderimage_3.border.top.setValue(4);
    borderimage_3_x_anchor_binding.init<Slider, &Slider::borderimage_3_x_anchor_binding>(borderimage_3.x);
    borderimage_3.x.setBinding(&borderimage_3_x_anchor_binding);
    // width: 9
    // line 104  "Slider.qml"
    borderimage_3.width.setValue(9);
    borderimage_3_height_binding.init<Slider, &Slider::borderimage_3_height_binding>(borderimage_3.height);
    // height: parent.height
    // line 103  "Slider.qml"
    borderimage_3.height.setBinding (&borderimage_3_height_binding);
    // BorderImage {
    // line 113  "Slider.qml"
    appendChild(&this->item__4, &borderimage_4);
    // source: "qrc:/images/slider-progress-vertical.png"
    // line 121  "Slider.qml"
    borderimage_4.source.setValue(Qul::Private::ImagePrivate::fromRasterBuffer(qul_rasterBuffer_slider_2Dprogress_2Dvertical_17367687796409029701_handle));
    // border.bottom: 4
    // line 120  "Slider.qml"
    borderimage_4.border.bottom.setValue(4);
    // border.top: 4
    // line 119  "Slider.qml"
    borderimage_4.border.top.setValue(4);
    borderimage_4_x_anchor_binding.init<Slider, &Slider::borderimage_4_x_anchor_binding>(borderimage_4.x);
    borderimage_4.x.setBinding(&borderimage_4_x_anchor_binding);
    borderimage_4_y_anchor_binding.init<Slider, &Slider::borderimage_4_y_anchor_binding>(borderimage_4.y);
    borderimage_4.y.setBinding(&borderimage_4_y_anchor_binding);
    // width: 9
    // line 116  "Slider.qml"
    borderimage_4.width.setValue(9);
    borderimage_4_height_binding.init<Slider, &Slider::borderimage_4_height_binding>(borderimage_4.height);
    // height: parent.height - handle.y - (handle.implicitHeight / 2)
    // line 115  "Slider.qml"
    borderimage_4.height.setBinding (&borderimage_4_height_binding);
    borderimage_4_visible_binding.init<Slider, &Slider::borderimage_4_visible_binding>(borderimage_4.visible);
    // visible: control.enabled && control.visualPosition < 1
    // line 114  "Slider.qml"
    borderimage_4.visible.setBinding (&borderimage_4_visible_binding);
    // background: Item {
    // line 68  "Slider.qml"
    background.setValue(&item__2);
    item__implicitHeight_binding.init<Slider, &Slider::item__implicitHeight_binding>(item_.itemExtraProperties->implicitHeight);
    // implicitHeight: handleImage.implicitHeight - 20
    // line 50  "Slider.qml"
    item_.itemExtraProperties->implicitHeight.setBinding (&item__implicitHeight_binding);
    item__implicitWidth_binding.init<Slider, &Slider::item__implicitWidth_binding>(item_.itemExtraProperties->implicitWidth);
    // implicitWidth: handleImage.implicitWidth - 20
    // line 48  "Slider.qml"
    item_.itemExtraProperties->implicitWidth.setBinding (&item__implicitWidth_binding);
    item__y_binding.init<Slider, &Slider::item__y_binding>(item_.y);
    // y: control.orientation == Qt.Vertical ? control.visualPosition * (parent.availableHeight - handleImage.implicitHeight / 2) + parent.topInset : (parent.height / 2 - implicitHeight / 2)
    // line 46  "Slider.qml"
    item_.y.setBinding (&item__y_binding);
    item__x_binding.init<Slider, &Slider::item__x_binding>(item_.x);
    // x: control.orientation == Qt.Horizontal ? control.visualPosition * (parent.availableWidth - handleImage.implicitWidth / 2) + parent.leftInset : (parent.width / 2 - implicitWidth / 2)
    // line 45  "Slider.qml"
    item_.x.setBinding (&item__x_binding);
    // Image {
    // line 52  "Slider.qml"
    appendChild(&this->item_, &handleImage);
    handleImage_x_anchor_binding.init<Slider, &Slider::handleImage_x_anchor_binding>(handleImage.x);
    handleImage.x.setBinding(&handleImage_x_anchor_binding);
    handleImage_y_anchor_binding.init<Slider, &Slider::handleImage_y_anchor_binding>(handleImage.y);
    handleImage.y.setBinding(&handleImage_y_anchor_binding);
    handleImage_source_binding.init<Slider, &Slider::handleImage_source_binding>(handleImage.source);
    // source: control.enabled
    // line 54  "Slider.qml"
    handleImage.source.setBinding (&handleImage_source_binding);
    // handle: Item {
    // line 44  "Slider.qml"
    handle.setValue(&item_);
    // bottomPadding: DefaultStyle.padding - 3
    // line 40  "Slider.qml"
    bottomPadding.setValue(2);
    // rightPadding: DefaultStyle.padding - 1
    // line 39  "Slider.qml"
    rightPadding.setValue(4);
    // topPadding: DefaultStyle.padding - 3
    // line 38  "Slider.qml"
    topPadding.setValue(2);
    // leftPadding: DefaultStyle.padding - 1
    // line 37  "Slider.qml"
    leftPadding.setValue(4);
    // bottomInset: DefaultStyle.inset - 3
    // line 36  "Slider.qml"
    bottomInset.setValue(2);
    // rightInset: DefaultStyle.inset - 1
    // line 35  "Slider.qml"
    rightInset.setValue(4);
    // topInset: DefaultStyle.inset - 3
    // line 34  "Slider.qml"
    topInset.setValue(2);
    // leftInset: DefaultStyle.inset - 1
    // line 33  "Slider.qml"
    leftInset.setValue(4);
    _implicitHeight_binding.init<Slider, &Slider::_implicitHeight_binding>(itemExtraProperties->implicitHeight);
    // implicitHeight: Math.max((background ? background.implicitHeight : 0) + topInset + bottomInset,
    // line 30  "Slider.qml"
    itemExtraProperties->implicitHeight.setBinding (&_implicitHeight_binding);
    _implicitWidth_binding.init<Slider, &Slider::_implicitWidth_binding>(itemExtraProperties->implicitWidth);
    // implicitWidth: Math.max((background ? background.implicitWidth : 0) + leftInset + rightInset,
    // line 28  "Slider.qml"
    itemExtraProperties->implicitWidth.setBinding (&_implicitWidth_binding);
}

} // namespace QtQuick
} // namespace Controls
} // namespace StyleDefault
