// This code is auto-generated by Qul's qmltocpp tool from the file 'SwipeView.qml'
// WARNING! All changes made in this file will be lost!
// NOTE: This generated API is to be considered implementation detail for Qul.
//       It may change from version to version and should not be relied upon.
#pragma once
#include <platforminterface/log.h>
#include <qul/image.h>
#include <qul/private/builtins.h>
#include <qul/private/controls/swipeviewtemplate.h>
#include <qul/private/file.h>
#include <qul/private/flickable.h>
#include <qul/private/items.h>
#include <qul/private/qulrcc_lookup.h>
#include <qul/private/unicodestring.h>
#include <qul/signal.h>

namespace QtQuick {
namespace Controls {
namespace StyleDefault {

struct SwipeView : Qul::Private::Controls::Templates::SwipeView , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Controls::Templates::SwipeView  > {
    SwipeView();


    Qul::Property<Qul::Private::String> state;
    struct flickable_Flickable : Qul::Private::Items::Flickable , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Flickable  > {
        flickable_Flickable()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Flickable  >(this)
        {}
    } flickable;
    struct SwipeView_1609415993_bindingFunctor {
        bool operator()(SwipeView *self) const;
    };
    Qul::Private::Binding<SwipeView_1609415993_bindingFunctor, 0> flickable_interactive_binding;
    struct SwipeView_638361119_bindingFunctor {
        int operator()(SwipeView *self) const;
    };
    Qul::Private::Binding<SwipeView_638361119_bindingFunctor, 0> _implicitHeight_binding;
    struct SwipeView_2791446706_bindingFunctor {
        int operator()(SwipeView *self) const;
    };
    Qul::Private::Binding<SwipeView_2791446706_bindingFunctor, 0> _implicitWidth_binding;
};

} // namespace QtQuick
} // namespace Controls
} // namespace StyleDefault
