// This code is auto-generated by Qul's qmltocpp tool from the file 'Switch.qml'
// WARNING! All changes made in this file will be lost!
// NOTE: This generated API is to be considered implementation detail for Qul.
//       It may change from version to version and should not be relied upon.
#pragma once
#include "DefaultStyle.h"
#include <platforminterface/log.h>
#include <qul/image.h>
#include <qul/private/animation.h>
#include <qul/private/builtins.h>
#include <qul/private/controls/switchtemplate.h>
#include <qul/private/extras/colorizedimage.h>
#include <qul/private/file.h>
#include <qul/private/items.h>
#include <qul/private/items/item.h>
#include <qul/private/items/text.h>
#include <qul/private/qulrcc_lookup.h>
#include <qul/private/unicodestring.h>
#include <qul/signal.h>

namespace QtQuick {
namespace Controls {
namespace StyleDefault {

struct Switch : Qul::Private::Controls::Templates::Switch , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Controls::Templates::Switch  > {
    Switch();


    Qul::Property<Qul::Private::String> state;
    struct item__2_Item : Qul::Private::Items::Item , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Item  > {
        item__2_Item()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Item  >(this)
        {}
    } item__2;
    typedef Qul::Private::Items::TextLight  text__Text;
    text__Text text_;
    struct row_Row : Qul::Private::Items::Row , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Row  > {
        row_Row()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Row  >(this)
        {}
    } row;
    struct item__Item : Qul::Private::Items::Item , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Item  > {
        item__Item()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Item  >(this)
        {}
    } item_;
    typedef Qul::Private::Items::Image  image_Image;
    image_Image image;
    typedef Qul::Private::Items::Image  image_2_Image;
    image_2_Image image_2;
    typedef Qul::Private::Items::NumberAnimation <int> numberanimation_NumberAnimation;
    numberanimation_NumberAnimation numberanimation;
    typedef Qul::Private::BehaviorLight <int> behavior_Behavior;
    behavior_Behavior behavior;
    typedef Qul::Private::Items::Image  image_3_Image;
    image_3_Image image_3;
    struct colorizedimage_ColorizedImage : Qul::Private::Items::ColorizedImage , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::ColorizedImage  > {
        colorizedimage_ColorizedImage()
            : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::ColorizedImage  >(this)
        {}
    } colorizedimage;
    struct Switch_1035992415_bindingFunctor {
        int operator()(Switch *self) const;
    };
    Qul::Private::Binding<Switch_1035992415_bindingFunctor, 0> item__2_implicitWidth_binding;
    struct text__y_anchor_bindingFunctor {
    int operator()(Switch *self) const;
};
    Qul::Private::Binding<text__y_anchor_bindingFunctor, 2> text__y_anchor_binding;
    struct Switch_654254210_bindingFunctor {
        Qul::PlatformInterface::Rgba32 operator()(Switch *self) const;
    };
    Qul::Private::Binding<Switch_654254210_bindingFunctor, 0> text__color_binding;
    struct Switch_3537330082_bindingFunctor {
        Qul::Private::FontPointer operator()(Switch *self) const;
    };
    Qul::Private::Binding<Switch_3537330082_bindingFunctor, 0> font_font_binding;
    struct Switch_65258397_bindingFunctor {
        Qul::Private::String operator()(Switch *self) const;
    };
    Qul::Private::Binding<Switch_65258397_bindingFunctor, 0> text__text_binding;
    struct Switch_4147903454_bindingFunctor {
        Qul::PlatformInterface::Rgba32 operator()(Switch *self) const;
    };
    Qul::Private::Binding<Switch_4147903454_bindingFunctor, 0> colorizedimage_color_binding;
    struct Switch_4169422798_bindingFunctor {
        int operator()(Switch *self) const;
    };
    Qul::Private::Binding<Switch_4169422798_bindingFunctor, 0> colorizedimage_y_binding;
    struct Switch_4260820959_bindingFunctor {
        int operator()(Switch *self) const;
    };
    Qul::Private::Binding<Switch_4260820959_bindingFunctor, 0> colorizedimage_x_binding;
    struct image_y_anchor_bindingFunctor {
    int operator()(Switch *self) const;
};
    Qul::Private::Binding<image_y_anchor_bindingFunctor, 2> image_y_anchor_binding;
    struct Switch_1347771666_bindingFunctor {
        int operator()(Switch *self) const;
    };
    Qul::Private::Binding<Switch_1347771666_bindingFunctor, 0> image_x_binding;
    struct image_2_y_anchor_bindingFunctor {
    int operator()(Switch *self) const;
};
    Qul::Private::Binding<image_2_y_anchor_bindingFunctor, 2> image_2_y_anchor_binding;
    struct Switch_1553820945_bindingFunctor {
        int operator()(Switch *self) const;
    };
    Qul::Private::Binding<Switch_1553820945_bindingFunctor, 0> image_2_x_binding;
    struct image_3_y_anchor_bindingFunctor {
    int operator()(Switch *self) const;
};
    Qul::Private::Binding<image_3_y_anchor_bindingFunctor, 2> image_3_y_anchor_binding;
    struct Switch_3334378452_bindingFunctor {
        int operator()(Switch *self) const;
    };
    Qul::Private::Binding<Switch_3334378452_bindingFunctor, 0> image_3_x_binding;
    struct Switch_3560203182_bindingFunctor {
        int operator()(Switch *self) const;
    };
    Qul::Private::Binding<Switch_3560203182_bindingFunctor, 0> _implicitHeight_binding;
    struct Switch_2791446706_bindingFunctor {
        int operator()(Switch *self) const;
    };
    Qul::Private::Binding<Switch_2791446706_bindingFunctor, 0> _implicitWidth_binding;
};

} // namespace QtQuick
} // namespace Controls
} // namespace StyleDefault
