// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!

#include <qul/pixelformat.h>

namespace Qul {
namespace Private {

Qul::PixelFormat preferredOpaquePixelFormat = PixelFormat_RGB32;
Qul::PixelFormat preferredAlphaPixelFormat = PixelFormat_ARGB32;

} // namespace Private
} // namespace Qul
