// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!

#include <qul/private/qulrcc_lookup.h>

extern const Qul::Private::RasterBuffer *const qul_rasterBuffer_p506_5F133413_16142385033138834515_handle;


namespace Qul {
namespace Private {

const ImageAssetLookupEntry qrcImageLookupSize[] = {
    {22, 0, 0},
    {0, 0, 0}
};

const ImageAssetLookupEntry qrcImageLookupHash[] = {
    {0x366eaed8, 0, 65535}, // images/p506_133413.png
    {0x00000000, 0, 0}
};

const RasterBuffer *const qrcImageLookupDirect[] = {
    qul_rasterBuffer_p506_5F133413_16142385033138834515_handle,
    NULL
};

const quint16 qrcImageLookupSizeLength = 1;


} // namespace Private
} // namespace Qul
