// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!

#include <qul/private/qulrcc_runtimeallocation.h>

namespace Qul {
namespace Private {

const quint8 QUL_NUM_RUNTIME_ALLOCATION_TYPES = 0;

const RuntimeAllocationTypeInfo qulRuntimeAllocationTypeInfo[] = {
    {0, 0}
};

ResourceCache *qulResourceCaches[] = {
    NULL
};

} // namespace Private
} // namespace Qul
