/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "deviceinformationexchangeprotocol.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(HostToDeviceMessage, HostToDeviceMessage, AUTO)


PB_BIND(DeviceToHostMessage, DeviceToHostMessage, AUTO)


PB_BIND(ConsoleLog, ConsoleLog, AUTO)


PB_BIND(TouchSequence, TouchSequence, AUTO)


PB_BIND(TouchEvent, TouchEvent, AUTO)


PB_BIND(GetFramebufferData, GetFramebufferData, AUTO)


PB_BIND(DataTransfer, DataTransfer, AUTO)


PB_BIND(DataTransferDone, DataTransferDone, AUTO)


PB_BIND(DataTransferFailed, DataTransferFailed, AUTO)



